export type AcademyLocale = "fr" | "en";

export type AcademyCourse = {
  code: string;
  domain: string;
  type: "Technology" | "Methods" | "Responsible Digital";
  duration: string;
  formats: Array<"Inter-company" | "In-company" | "Custom">;
  title: Record<AcademyLocale, string>;
  description: Record<AcademyLocale, string>;
};

const allFormats: AcademyCourse["formats"] = ["Inter-company", "In-company", "Custom"];

export const academyDomains = ["Product & Design", "Software Engineering", "Cloud & Platforms", "Data & AI", "Agile & Lean", "Transformation", "Soft Skills"];

export const academyCourses: AcademyCourse[] = [
  { code: "PD-01", domain: "Product & Design", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Product discovery et validation d’opportunité", en: "Product discovery and opportunity validation" }, description: { fr: "Transformer une idée en hypothèses testables et en décisions produit étayées.", en: "Turn an idea into testable assumptions and evidence-based product decisions." } },
  { code: "PD-02", domain: "Product & Design", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Product management orienté impact", en: "Impact-driven product management" }, description: { fr: "Prioriser, piloter et mesurer un produit à partir de la valeur créée.", en: "Prioritise, steer and measure a product through the value it creates." } },
  { code: "PD-03", domain: "Product & Design", type: "Technology", duration: "1 day", formats: ["In-company", "Custom"], title: { fr: "OKR : des objectifs à l’exécution", en: "OKRs: from objectives to execution" }, description: { fr: "Déployer des objectifs lisibles et des résultats clés réellement pilotables.", en: "Deploy clear objectives and genuinely actionable key results." } },
  { code: "PD-04", domain: "Product & Design", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "UX Design et prototypage avec Figma", en: "UX design and prototyping with Figma" }, description: { fr: "Concevoir et tester des interfaces utiles, accessibles et cohérentes.", en: "Design and test useful, accessible and consistent interfaces." } },
  { code: "SE-01", domain: "Software Engineering", type: "Technology", duration: "3 days", formats: allFormats, title: { fr: "Clean Code, tests et refactoring", en: "Clean code, testing and refactoring" }, description: { fr: "Faire évoluer un code existant avec plus de confiance et de qualité.", en: "Evolve existing code with greater confidence and quality." } },
  { code: "SE-02", domain: "Software Engineering", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Domain-Driven Design en pratique", en: "Domain-driven design in practice" }, description: { fr: "Aligner modèle métier, architecture et collaboration autour des domaines clés.", en: "Align business models, architecture and collaboration around core domains." } },
  { code: "SE-03", domain: "Software Engineering", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Concevoir des APIs robustes et sécurisées", en: "Designing robust and secure APIs" }, description: { fr: "Appliquer les standards, patterns et contrôles essentiels d’une API moderne.", en: "Apply the essential standards, patterns and controls of a modern API." } },
  { code: "SE-04", domain: "Software Engineering", type: "Technology", duration: "2 days", formats: ["In-company", "Custom"], title: { fr: "Architecture logicielle évolutive", en: "Evolutionary software architecture" }, description: { fr: "Faire évoluer l’architecture au rythme du produit et de ses contraintes.", en: "Evolve architecture at the pace of the product and its constraints." } },
  { code: "SE-05", domain: "Software Engineering", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Développement mobile avec Swift iOS", en: "Mobile development with Swift for iOS" }, description: { fr: "Construire une application iOS moderne avec Swift et les pratiques de qualité essentielles.", en: "Build a modern iOS application with Swift and essential quality practices." } },
  { code: "CP-01", domain: "Cloud & Platforms", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Fondamentaux du cloud et architectures modernes", en: "Cloud fundamentals and modern architectures" }, description: { fr: "Comprendre les modèles cloud et faire des choix d’architecture éclairés.", en: "Understand cloud models and make informed architecture choices." } },
  { code: "CP-02", domain: "Cloud & Platforms", type: "Technology", duration: "3 days", formats: allFormats, title: { fr: "Kubernetes : déployer et opérer", en: "Kubernetes: deploy and operate" }, description: { fr: "Conteneuriser, déployer et administrer des applications en production.", en: "Containerise, deploy and operate production applications." } },
  { code: "CP-03", domain: "Cloud & Platforms", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Infrastructure as Code avec Terraform", en: "Infrastructure as code with Terraform" }, description: { fr: "Rendre les infrastructures reproductibles, contrôlées et maintenables.", en: "Make infrastructure reproducible, controlled and maintainable." } },
  { code: "CP-04", domain: "Cloud & Platforms", type: "Technology", duration: "2 days", formats: ["In-company", "Custom"], title: { fr: "DevOps, CI/CD et observabilité", en: "DevOps, CI/CD and observability" }, description: { fr: "Fluidifier la livraison et piloter la fiabilité par les données d’exploitation.", en: "Streamline delivery and manage reliability through operational data." } },
  { code: "DA-01", domain: "Data & AI", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "Data literacy pour décideurs", en: "Data literacy for decision-makers" }, description: { fr: "Développer une culture commune pour décider et collaborer avec la donnée.", en: "Build a shared culture for data-driven decisions and collaboration." } },
  { code: "DA-02", domain: "Data & AI", type: "Technology", duration: "3 days", formats: allFormats, title: { fr: "Fondamentaux de la Data Science", en: "Data science fundamentals" }, description: { fr: "Structurer une première démarche d’analyse, de modélisation et d’évaluation.", en: "Structure an initial analysis, modelling and evaluation workflow." } },
  { code: "DA-03", domain: "Data & AI", type: "Technology", duration: "2 days", formats: allFormats, title: { fr: "IA générative : usages, risques et prototypage", en: "Generative AI: use cases, risks and prototyping" }, description: { fr: "Identifier les cas d’usage utiles et prototyper une solution responsable.", en: "Identify valuable use cases and prototype a responsible solution." } },
  { code: "DA-04", domain: "Data & AI", type: "Technology", duration: "3 days", formats: ["In-company", "Custom"], title: { fr: "MLOps : industrialiser les modèles", en: "MLOps: industrialising models" }, description: { fr: "Déployer, observer et faire évoluer des modèles de machine learning.", en: "Deploy, observe and evolve machine-learning models." } },
  { code: "AL-01", domain: "Agile & Lean", type: "Methods", duration: "2 days", formats: allFormats, title: { fr: "Fondamentaux de l’Agile", en: "Agile fundamentals" }, description: { fr: "Comprendre les principes agiles et les appliquer à un contexte réel.", en: "Understand agile principles and apply them to a real context." } },
  { code: "AL-02", domain: "Agile & Lean", type: "Methods", duration: "2 days", formats: allFormats, title: { fr: "Product Owner : posture et pratiques", en: "Product owner: mindset and practices" }, description: { fr: "Piloter la valeur, collaborer avec l’équipe et arbitrer avec clarté.", en: "Drive value, collaborate with the team and make clear trade-offs." } },
  { code: "AL-03", domain: "Agile & Lean", type: "Methods", duration: "2 days", formats: allFormats, title: { fr: "Scrum Master et facilitation d’équipe", en: "Scrum master and team facilitation" }, description: { fr: "Faire progresser une équipe par la facilitation et l’amélioration continue.", en: "Help a team progress through facilitation and continuous improvement." } },
  { code: "TR-01", domain: "Transformation", type: "Methods", duration: "2 days", formats: ["In-company", "Custom"], title: { fr: "Stratégie de transformation digitale", en: "Digital transformation strategy" }, description: { fr: "Relier ambition, capacités, portefeuille d’initiatives et trajectoire d’exécution.", en: "Connect ambition, capabilities, initiative portfolio and delivery roadmap." } },
  { code: "TR-02", domain: "Transformation", type: "Methods", duration: "1 day", formats: ["In-company", "Custom"], title: { fr: "Conduite du changement pragmatique", en: "Pragmatic change management" }, description: { fr: "Créer les conditions d’appropriation et mesurer l’adoption dans la durée.", en: "Create the conditions for adoption and measure it over time." } },
  { code: "SS-01", domain: "Soft Skills", type: "Methods", duration: "1 day", formats: allFormats, title: { fr: "Feedback et communication impactante", en: "Feedback and impactful communication" }, description: { fr: "Améliorer la qualité des échanges et faire progresser la coopération.", en: "Improve the quality of interactions and strengthen cooperation." } },
  { code: "SS-02", domain: "Soft Skills", type: "Methods", duration: "2 days", formats: ["In-company", "Custom"], title: { fr: "Faciliter des ateliers complexes", en: "Facilitating complex workshops" }, description: { fr: "Préparer et animer des temps collectifs qui produisent des décisions.", en: "Prepare and run collaborative sessions that lead to decisions." } },
  { code: "NR-01", domain: "Transformation", type: "Responsible Digital", duration: "2 days", formats: allFormats, title: { fr: "Écoconception de services numériques", en: "Eco-design of digital services" }, description: { fr: "Réduire les impacts dès la conception et suivre des critères concrets.", en: "Reduce impacts from the design stage and track concrete criteria." } },
  { code: "NR-02", domain: "Product & Design", type: "Responsible Digital", duration: "1 day", formats: allFormats, title: { fr: "Accessibilité numérique : les fondamentaux", en: "Digital accessibility fundamentals" }, description: { fr: "Intégrer l’accessibilité dans le produit, le design et la recette.", en: "Embed accessibility in product, design and quality assurance." } },
  { code: "NR-03", domain: "Data & AI", type: "Responsible Digital", duration: "1 day", formats: ["In-company", "Custom"], title: { fr: "IA responsable et gouvernance", en: "Responsible AI and governance" }, description: { fr: "Encadrer les risques, les responsabilités et le suivi des systèmes d’IA.", en: "Manage the risks, responsibilities and oversight of AI systems." } },
  { code: "NR-04", domain: "Cloud & Platforms", type: "Responsible Digital", duration: "1 day", formats: ["In-company", "Custom"], title: { fr: "Cloud responsable et FinOps", en: "Responsible cloud and FinOps" }, description: { fr: "Croiser performance, coûts et sobriété dans les décisions cloud.", en: "Balance performance, cost and efficiency in cloud decisions." } },
];
