export const servicesEn = [
  { id: "consulting", number: "01", title: "Business & Technology Consulting", short: "Business & Technology Consulting", summary: "Set a clear direction for transformation, from digital strategy to resilient architecture and governance.", tagline: "Decide with a clear view of value, risk and direction.", description: "We turn business and technology priorities into a realistic roadmap that connects objectives, user experience, architecture and governance.", capabilities: ["Digital and technology maturity assessment", "Target vision and roadmap", "Programme framing and business cases", "Enterprise and solution architecture", "API strategy and governance", "Change enablement"], outcomes: "Shared priorities, documented decisions, a clear roadmap and anticipated risks." },
  { id: "digital-data", number: "02", title: "Digital & Data Factory", short: "Digital & Data Factory", summary: "Turn ideas into digital products and data into decisions, from prototype through industrialisation.", tagline: "Turn an opportunity into a useful digital product, quickly.", description: "Our product, design, engineering and data specialists work together to design, validate, deliver and scale user-centred digital experiences.", capabilities: ["Product discovery and user research", "UX/UI design and design systems", "Web, mobile and portal applications", "Backends, APIs and microservices", "Data platforms, pipelines and governance", "Analytics, AI and automation"], outcomes: "Faster time to market, stronger adoption, better use of data and a maintainable foundation." },
  { id: "engineering", number: "03", title: "Squad As Service", short: "Squad As Service", summary: "Reduce time to market with multidisciplinary squads applying proven Agile practices.", tagline: "Turn your ambitions into outcomes with an accountable end-to-end squad.", description: "Our Squad As Service model brings together the product, design, engineering, quality and DevOps skills required for your context. The squad integrates with your organisation, owns a clear scope and delivers across the full product lifecycle, from discovery through production and continuous improvement.", capabilities: ["Squad composition tailored to product goals", "Product management, discovery and backlog ownership", "Agile ways of working, rituals and continuous improvement", "UX/UI, frontend, backend and mobile development", "Architecture, system integration and APIs", "Testing, automation, security and performance", "DevOps, production, documentation and knowledge transfer"], outcomes: "Shorter time to market, flexible delivery capacity, greater visibility, built-in quality and continuous product improvement." },
  { id: "cloud-devops", number: "04", title: "DevSecOps & Cloud Engineering", short: "DevSecOps & Cloud Engineering", summary: "Accelerate releases and improve platform reliability through cloud, automation, built-in security and observability.", tagline: "Deliver confidently on a reliable, observable and secure platform.", description: "We support cloud modernisation and delivery industrialisation, from strategy through daily operations.", capabilities: ["Cloud assessment and strategy", "Cloud, hybrid and on-premise architecture", "CI/CD and deployment automation", "Infrastructure as Code", "Containers and Kubernetes", "Observability, SRE and continuity", "DevSecOps, secrets and cost optimisation"], outcomes: "Smoother delivery, reproducible environments, improved resilience and clearer costs." },
  { id: "academy", number: "05", title: "Paytium Academy", short: "Training & Academy", summary: "Grow your teams’ capabilities through practical training led by field experts.", tagline: "Learn today to build better tomorrow.", description: "Paytium Academy delivers courses in technology, product, data, cloud, Agile and management through practical, contextual learning.", capabilities: ["Inter-company courses", "In-company sessions", "Custom learning journeys", "Hands-on workshops and cases", "Management and operational programmes", "In-person, remote and hybrid delivery"], outcomes: "Immediately useful skills, a shared language and lasting team autonomy." },
];

export const methodsEn = [
  { number: "01", title: "Frame", text: "Understand the challenge, map the current state and define measurable outcomes.", deliverables: "Assessment · Target vision · Roadmap · Initial backlog" },
  { number: "02", title: "Design", text: "Co-design the experience, architecture and operating model with business and IT teams.", deliverables: "Journeys · Prototypes · Architecture · Delivery plan" },
  { number: "03", title: "Build", text: "Develop, integrate and test in short iterations with quality built in.", deliverables: "Working product · APIs · Automation · Documentation" },
  { number: "04", title: "Evolve", text: "Deploy, observe, secure and improve based on real usage and data.", deliverables: "Production · Observability · Handover · Improvement" },
];
