export const siteConfig = {
  contactEmail: "connect@paytium.io" as string | null,
  contactPhone: "+212 707-252336" as string | null,
  addressFr: "Casablanca" as string | null,
  addressEn: "Casablanca" as string | null,
  website: "paytium.io",
  linkedinUrl: "https://www.linkedin.com/company/paytium" as string | null,
  legalCompanyName: "Paytium",
  legalNoticeUrl: null as string | null,
  privacyUrl: null as string | null,
  contactEndpoint: process.env.VITE_CONTACT_ENDPOINT ?? "https://formsubmit.co/ajax/paytium.solutions@gmail.com",
};

export const services = [
  {
    id: "consulting",
    number: "01",
    title: "Business & Technology Consulting",
    short: "Conseil & stratégie",
    summary: "Donnez une direction claire à votre transformation, de la stratégie digitale à la définition d’architectures résilientes et gouvernées.",
    tagline: "Décider avec une vision claire de la valeur, des risques et de la trajectoire.",
    description: "Nous aidons les directions métier et IT à transformer leurs priorités en une feuille de route réaliste. Le cadrage relie objectifs business, expérience utilisateur, architecture, organisation et gouvernance.",
    capabilities: ["Diagnostic de maturité digitale et technologique", "Vision cible et feuille de route", "Cadrage de programmes et business cases", "Architecture d’entreprise, solution et intégration", "Stratégie API et gouvernance des échanges", "Accompagnement au changement et gouvernance"],
    outcomes: "Priorités partagées, décisions documentées, trajectoire lisible et risques anticipés.",
  },
  {
    id: "digital-data",
    number: "02",
    title: "Digital & Data Factory",
    short: "Digital, Data & IA",
    summary: "Transformez vos idées en produits numériques et vos données en leviers de décision, du prototype à l’industrialisation.",
    tagline: "Transformer rapidement une opportunité en produit numérique utile.",
    description: "Nos équipes produit, design, développement et data travaillent ensemble pour concevoir, tester, livrer et industrialiser des expériences digitales centrées sur l’usage.",
    capabilities: ["Product discovery, recherche utilisateur et prototypage", "UX/UI design et design systems", "Applications web, mobiles et portails", "Backend, APIs et microservices", "Data platforms, pipelines, qualité et gouvernance", "Analytics, IA et automatisation", "MVP, passage à l’échelle et modernisation"],
    outcomes: "Délai de mise sur le marché réduit, adoption renforcée, données mieux exploitées et socle maintenable.",
  },
  {
    id: "engineering",
    number: "03",
    title: "Squad As Service",
    short: "Squad As Service",
    summary: "Réduisez vos délais de mise sur le marché grâce à des squads pluridisciplinaires adoptant les bonnes pratiques Agile.",
    tagline: "Concrétisez vos ambitions avec une squad engagée de bout en bout.",
    description: "Notre modèle Squad As Service réunit les compétences produit, design, engineering, qualité et DevOps nécessaires à votre contexte. La squad s’intègre à votre organisation, prend en charge un périmètre clair et assure une exécution maîtrisée sur tout le cycle de vie produit, de la discovery à la mise en production et à l’amélioration continue.",
    capabilities: ["Composition de squad adaptée au produit et aux objectifs", "Product management, discovery et pilotage du backlog", "Organisation Agile, rituels et amélioration continue", "UX/UI, développement frontend, backend et mobile", "Architecture, intégration de systèmes et APIs", "Tests, automatisation, sécurité et performance", "DevOps, mise en production, documentation et transfert"],
    outcomes: "Time-to-market réduit, capacité de delivery flexible, visibilité renforcée, qualité intégrée et produit amélioré en continu.",
  },
  {
    id: "cloud-devops",
    number: "04",
    title: "DevOps & Cloud Engineering",
    short: "Cloud & DevOps",
    summary: "Accélérez vos livraisons et fiabilisez vos environnements grâce à l’automatisation, au cloud et à l’observabilité.",
    tagline: "Livrer plus sereinement sur une plateforme fiable, observable et sécurisée.",
    description: "Nous accompagnons la modernisation des environnements et l’industrialisation du cycle de livraison, de la stratégie cloud à l’exploitation quotidienne.",
    capabilities: ["Assessment et stratégie Move-to-Cloud", "Architecture cloud, hybride ou on-premise", "CI/CD et automatisation des déploiements", "Infrastructure as Code", "Conteneurs, Kubernetes et platform engineering", "Observabilité, SRE et continuité", "DevSecOps, secrets et optimisation des coûts"],
    outcomes: "Livraisons plus fluides, environnements reproductibles, meilleure résilience et coûts plus visibles.",
  },
  {
    id: "academy",
    number: "05",
    title: "Paytium Academy",
    short: "Formation & Academy",
    summary: "Faites monter vos équipes en compétences grâce à des formations pratiques animées par des experts du terrain.",
    tagline: "Apprendre aujourd’hui pour mieux construire demain.",
    description: "Paytium Academy propose des formations technologiques, produit, data, cloud, agiles et managériales. Chaque parcours associe apports ciblés, ateliers pratiques et cas proches de votre réalité métier.",
    capabilities: ["Formations inter-entreprises", "Sessions intra-entreprise", "Parcours sur mesure", "Ateliers pratiques et études de cas", "Programmes pour managers et équipes opérationnelles", "Formats en présentiel, à distance ou hybrides"],
    outcomes: "Compétences immédiatement mobilisables, langage commun et autonomie durable des équipes.",
    href: "/academy",
  },
];

export const methods = [
  { number: "01", title: "Cadrer", text: "Comprendre les enjeux, cartographier l’existant, prioriser les cas d’usage et définir des résultats mesurables.", deliverables: "Diagnostic · Vision cible · Feuille de route · Backlog initial" },
  { number: "02", title: "Concevoir", text: "Co-construire l’expérience, l’architecture et le modèle opérationnel avec les équipes métier et IT.", deliverables: "Parcours · Prototypes · Architecture · Plan de livraison" },
  { number: "03", title: "Construire", text: "Développer, intégrer et tester par itérations courtes avec une qualité intégrée dès le départ.", deliverables: "Produit opérationnel · APIs · Automatisation · Documentation" },
  { number: "04", title: "Faire évoluer", text: "Déployer, observer, sécuriser et améliorer la solution à partir des usages et des données réelles.", deliverables: "Mise en production · Observabilité · Transfert · Amélioration" },
];

export const technologies = [
  { title: "Backend", items: ["Java", "Jakarta EE", "Spring", "Node.js", "Express", "NestJS"] },
  { title: "Frontend & Desktop", items: ["React", "Angular", "Gatsby", "Tailwind CSS", "Electron", "Next.js", "Remix", "Webpack"] },
  { title: "Mobile", items: ["React Native", "Android", "Swift iOS"] },
  { title: "UI / UX", items: ["Figma", "Balsamiq", "InVision", "Marvel", "Adobe Photoshop", "Adobe Illustrator"] },
  { title: "Data & Analytics", items: ["Hadoop", "Spark", "Python", "Kafka", "Airflow", "Cassandra", "Flask", "Dash"] },
  { title: "DevOps", items: ["Jenkins", "GitLab CI", "CircleCI", "Ansible", "Terraform", "Docker", "Puppet", "Chef"] },
  { title: "Testing", items: ["Xray", "Jest", "JUnit", "Mockito", "Selenium", "TestFairy"] },
  { title: "Bases de données", items: ["PostgreSQL", "Oracle", "MySQL", "SQL Server", "MongoDB", "Redis", "SQLite", "Elasticsearch"] },
  { title: "Cloud & Intégrations", items: ["AWS", "Microsoft Azure", "Google Cloud", "Heroku", "Kubernetes"] },
  { title: "Produit & Agilité", items: ["Lean Startup", "Product framing", "Product design", "Design Thinking", "Scrum", "Scaled Agile"] },
  { title: "API Gateway", items: ["Kong", "Apigee", "WSO2", "Amazon API Gateway", "Spring Cloud Gateway"] },
  { title: "Outils & Plateforme", items: ["Jira", "Confluence", "GitLab", "Bitbucket", "RabbitMQ", "MinIO", "Zabbix", "Nexus", "SonarQube"] },
];

export const workingMethods = [
  ["Product Thinking", "Partir du problème, des utilisateurs et de la valeur attendue."],
  ["Design Thinking", "Explorer, prototyper et tester avant d’industrialiser."],
  ["Agile Delivery", "Livrer par incréments, partager les arbitrages et apprendre rapidement."],
  ["DevSecOps", "Automatiser la qualité, la sécurité et la livraison dans le cycle."],
  ["Data-driven improvement", "Utiliser les métriques d’usage, de qualité et d’exploitation pour progresser."],
  ["Co-construction & transfert", "Associer les équipes clientes et renforcer leur autonomie."],
];
