export const siteConfig = {
  contactEmail: "connect@paytium.io" as string | null,
  contactPhone: "+212 707-252336" as string | null,
  addressFr: "Casablanca, Maroc" as string | null,
  addressEn: "Casablanca, Morocco" as string | null,
  website: "paytium.io",
  linkedinUrl: "https://www.linkedin.com/company/paytium" as string | null,
  legalCompanyName: "Paytium",
  legalNoticeUrl: null as string | null,
  privacyUrl: null as string | null,
  contactEndpoint: process.env.VITE_CONTACT_ENDPOINT ?? "https://formsubmit.co/ajax/paytium.solutions@gmail.com",
};

export const services = [
  {
    id: "consulting",
    number: "01",
    title: "Business & Technology Consulting",
    short: "Business & Technology Consulting",
    summary: "Clarifiez, cadrez et sécurisez vos décisions technologiques avant d’engager les budgets et les programmes structurants.",
    tagline: "Prendre les bonnes décisions technologiques, au bon niveau d’investissement.",
    description: "Nous accompagnons les directions générales, métiers et IT dans les décisions qui engagent durablement le système d’information. Nos consultants combinent vision stratégique, analyse de l’existant, architecture et connaissance du marché pour objectiver les scénarios, maîtriser les risques et construire une trajectoire exécutable.",
    capabilities: ["Conseil stratégique et diagnostic technologique", "Due diligence technologique", "Schéma directeur SI, digital et data", "Audit d’architecture et trajectoire de modernisation", "Cadrage, études d’opportunité et de faisabilité", "Benchmark de solutions, architectures et partenaires", "Stratégie API Management et gouvernance", "Business case, feuille de route et gouvernance de programme"],
    outcomes: "Des arbitrages objectivés, une architecture cible cohérente, des investissements priorisés et une feuille de route maîtrisée.",
  },
  {
    id: "digital-data",
    number: "02",
    title: "Digital & Data Factory",
    short: "Digital & Data Factory",
    summary: "Concevez et livrez des produits digitaux à fort impact avec des équipes hybrides sur mesure et un engagement adapté à vos objectifs.",
    tagline: "De l’idée au run, livrer un produit utile, robuste et durable.",
    description: "Notre Digital & Data Factory prend en charge vos produits et projets d’intégration au forfait ou en régie forfaitisée. La réalisation s’appuie sur une démarche Agile, des livraisons incrémentales et l’implication continue de vos équipes. Après la mise en production, nous assurons la TMA corrective et évolutive ou organisons le transfert de compétences pour garantir votre autonomie.",
    capabilities: ["Product discovery, cadrage fonctionnel et architecture", "Développement sur mesure web, mobile, data et IA", "Projets d’intégration, APIs et interopérabilité", "Delivery au forfait ou en régie forfaitisée", "Pilotage Agile et livraisons incrémentales", "Qualité, automatisation des tests et mise en production", "TMA corrective, évolutive et optimisation continue", "Documentation, transfert de compétences et autonomie des équipes"],
    outcomes: "Un produit opérationnel livré avec visibilité, une qualité maîtrisée et un dispositif de maintenance ou de transfert adapté.",
  },
  {
    id: "engineering",
    number: "03",
    title: "Squad As Service",
    short: "Squad As Service",
    summary: "Renforcez votre organisation avec des capacités qualifiées, flexibles et immédiatement opérationnelles en régie ou en centre de services.",
    tagline: "Mobiliser rapidement les bons profils et sécuriser la performance du delivery.",
    description: "Squad As Service vous permet d’augmenter votre capacité de delivery sans alourdir votre organisation. Nous constituons des équipes ou mobilisons des profils qualifiés, intégrés à vos modes de fonctionnement, avec un pilotage adapté : régie, centre de services ou squad augmentée. Les compétences peuvent couvrir le produit, l’Agile, l’architecture, l’engineering, la QA et le DevSecOps.",
    capabilities: ["Centre de services avec engagements et pilotage", "Équipes en régie et capacité flexible", "Squads augmentées et pluridisciplinaires", "Profils qualifiés et rapidement opérationnels", "Renforcement de la performance du delivery", "Cellule d’architecture et expertise technique", "Profils Agile : Product Owner et Scrum Master", "QA, automatisation des tests et qualité intégrée"],
    outcomes: "Une capacité opérationnelle rapidement mobilisée, un delivery plus prévisible et des compétences ajustables selon votre roadmap.",
  },
  {
    id: "cloud-devops",
    number: "04",
    title: "DevSecOps & Cloud Engineering",
    short: "DevSecOps & Cloud Engineering",
    summary: "Industrialisez votre chaîne de développement et sécurisez vos mises en production avec une usine logicielle moderne, automatisée et observable.",
    tagline: "Faire de la plateforme de delivery un accélérateur de qualité et de sécurité.",
    description: "Nous auditons, concevons, mettons en place ou migrons votre usine de développement selon les pratiques de référence DevSecOps. De la gestion du code au déploiement, nous automatisons les contrôles, la sécurité, la création des environnements et l’observabilité pour réduire les délais et fiabiliser chaque release.",
    capabilities: ["Audit de maturité DevSecOps et diagnostic de l’usine existante", "Architecture cible et mise en place d’une usine logicielle industrialisée", "Migration et modernisation des chaînes de développement", "Pipelines CI/CD, GitOps et automatisation des déploiements", "SAST, SCA, analyse de code et gestion des secrets", "Gestion des dépôts de code et d’artefacts", "Infrastructure as Code et provisioning automatisé", "Kubernetes, OpenShift et platform engineering", "Cloud engineering, observabilité, SRE et FinOps"],
    outcomes: "Des releases plus fréquentes et plus sûres, des environnements reproductibles et une exploitation mieux maîtrisée.",
  },
  {
    id: "academy",
    number: "05",
    title: "Paytium Academy",
    short: "Formation & Academy",
    summary: "Faites monter vos équipes en compétences grâce à des formations pratiques animées par des experts du terrain.",
    tagline: "Apprendre aujourd’hui pour mieux construire demain.",
    description: "Paytium Academy propose des formations technologiques, produit, data, cloud, agiles et managériales. Chaque parcours associe apports ciblés, ateliers pratiques et cas proches de votre réalité métier.",
    capabilities: ["Formations inter-entreprises", "Sessions intra-entreprise", "Parcours sur mesure", "Ateliers pratiques et études de cas", "Programmes pour managers et équipes opérationnelles", "Formats en présentiel, à distance ou hybrides"],
    outcomes: "Compétences immédiatement mobilisables, langage commun et autonomie durable des équipes.",
    href: "/academy",
  },
];

export const methods = [
  { number: "01", title: "Vision", text: "Nous alignons la transformation sur vos priorités métier et vos objectifs." },
  { number: "02", title: "Architecture", text: "Nous concevons des architectures robustes, évolutives et adaptées à votre contexte." },
  { number: "03", title: "Build", text: "Nous développons et déployons des solutions digitales et data concrètes, fiables et performantes." },
  { number: "04", title: "Run", text: "Nous assurons la disponibilité, la sécurité et l’amélioration continue des solutions en production." },
  { number: "05", title: "Transfer", text: "Nous transmettons nos méthodes et nos savoir-faire pour renforcer durablement l’autonomie de vos équipes." },
];

export const technologies = [
  { title: "Ingénierie logicielle", items: ["React", "Angular", "Vue.js", "Gatsby", "Next.js", "Remix", "Tailwind CSS", "Webpack", "Electron", "Java", "Jakarta EE", "Spring", "PHP", "Python", "Node.js", "Express", "NestJS", "Swift / iOS", "Android", "Flutter", "React Native"] },
  { title: "Data & IA", items: ["Data Engineering", "Machine Learning", "GenAI", "NLP", "Computer Vision", "RPA", "Hadoop", "Spark", "Airflow", "Python", "Flask", "Dash"] },
  { title: "Cloud & Platform Engineering", items: ["Cloud Architecture", "AWS", "Microsoft Azure", "Google Cloud", "OpenShift", "Kubernetes", "Docker", "Heroku"] },
  { title: "DevSecOps", items: ["CI/CD", "Jenkins", "GitLab CI", "GitHub Actions", "CircleCI", "GitLab", "GitHub", "Bitbucket", "SonarQube", "Nexus Repository", "AWX", "Ansible", "Terraform", "Puppet", "Chef"] },
  { title: "API Management & Intégration", items: ["API Design", "Azure API Management (APIM)", "Kong", "Apigee", "WSO2", "Amazon API Gateway", "Spring Cloud Gateway"] },
  { title: "Cybersécurité", items: ["Security Architecture", "Audit & Compliance", "SOC", "IAM", "Secrets Management", "Application Security"] },
  { title: "Monitoring & Observabilité", items: ["Zabbix", "Prometheus", "Grafana", "Dynatrace", "OpenTelemetry", "Elastic Stack (ELK)"] },
  { title: "Collaboration", items: ["Miro", "Slack", "Microsoft Teams", "Notion"] },
  { title: "GED & Stockage objet", items: ["MinIO", "Alfresco"] },
  { title: "Brokers & Messaging", items: ["Kafka", "RabbitMQ"] },
  { title: "Bases de données", items: ["PostgreSQL", "Oracle", "MySQL", "SQL Server", "MongoDB", "Redis", "SQLite", "Cassandra", "Elasticsearch"] },
  { title: "Tests & Qualité", items: ["Xray", "Jest", "JUnit", "Mockito", "Selenium", "TestFairy", "QA Automation"] },
  { title: "UX & Product Design", items: ["UX/UI", "Product Design", "Digital Experience", "Figma", "Balsamiq", "InVision", "Marvel", "Adobe Photoshop", "Adobe Illustrator"] },
  { title: "Business & Delivery", items: ["AMOA", "Business Analysis", "Product framing", "Product Owner", "PMO", "Scrum", "Scrum Master", "Coach Agile", "QA", "Lean Startup", "Design Thinking", "Scaled Agile"] },
];

export const workingMethods = [
  ["Product Thinking", "Partir du problème, des utilisateurs et de la valeur attendue."],
  ["Design Thinking", "Explorer, prototyper et tester avant d’industrialiser."],
  ["Agile Delivery", "Livrer par incréments, partager les arbitrages et apprendre rapidement."],
  ["DevSecOps", "Automatiser la qualité, la sécurité et la livraison dans le cycle."],
  ["Data-driven improvement", "Utiliser les métriques d’usage, de qualité et d’exploitation pour progresser."],
  ["Co-construction & transfert", "Associer les équipes clientes et renforcer leur autonomie."],
];
