export const servicesEn = [
  { id: "consulting", number: "01", title: "Business & Technology Consulting", short: "Consulting & strategy", summary: "Set a clear direction for transformation, from digital strategy to resilient architecture and governance.", tagline: "Decide with a clear view of value, risk and direction.", description: "We turn business and technology priorities into a realistic roadmap that connects objectives, user experience, architecture and governance.", capabilities: ["Digital and technology maturity assessment", "Target vision and roadmap", "Programme framing and business cases", "Enterprise and solution architecture", "API strategy and governance", "Change enablement"], outcomes: "Shared priorities, documented decisions, a clear roadmap and anticipated risks." },
  { id: "digital-data", number: "02", title: "Digital & Data Factory", short: "Digital, Data & AI", summary: "Turn ideas into digital products and data into decisions, from prototype through industrialisation.", tagline: "Turn an opportunity into a useful digital product, quickly.", description: "Our product, design, engineering and data specialists work together to design, validate, deliver and scale user-centred digital experiences.", capabilities: ["Product discovery and user research", "UX/UI design and design systems", "Web, mobile and portal applications", "Backends, APIs and microservices", "Data platforms, pipelines and governance", "Analytics, AI and automation"], outcomes: "Faster time to market, stronger adoption, better use of data and a maintainable foundation." },
  { id: "engineering", number: "03", title: "Engineering & Technology", short: "Engineering", summary: "Deliver your ambitions through multidisciplinary teams and controlled end-to-end execution.", tagline: "Strengthen delivery with teams accountable for quality end to end.", description: "Paytium assembles the right delivery model for each project, with quality, security and knowledge transfer embedded throughout.", capabilities: ["Product management and delivery", "Agile organisation and improvement", "Frontend, backend and mobile development", "System integration", "Software architecture and technical reviews", "Testing, automation and performance"], outcomes: "Greater predictability, built-in quality, lower debt and more autonomous teams." },
  { id: "cloud-devops", number: "04", title: "DevOps & Cloud Engineering", short: "Cloud & DevOps", summary: "Accelerate releases and improve platform reliability through cloud, automation and observability.", tagline: "Deliver confidently on a reliable, observable and secure platform.", description: "We support cloud modernisation and delivery industrialisation, from strategy through daily operations.", capabilities: ["Cloud assessment and strategy", "Cloud, hybrid and on-premise architecture", "CI/CD and deployment automation", "Infrastructure as Code", "Containers and Kubernetes", "Observability, SRE and continuity"], outcomes: "Smoother delivery, reproducible environments, improved resilience and clearer costs." },
  { id: "academy", number: "05", title: "Paytium Academy", short: "Training & Academy", summary: "Grow your teams’ capabilities through practical training led by field experts.", tagline: "Learn today to build better tomorrow.", description: "Paytium Academy delivers courses in technology, product, data, cloud, Agile and management through practical, contextual learning.", capabilities: ["Inter-company courses", "In-company sessions", "Custom learning journeys", "Hands-on workshops and cases", "Management and operational programmes", "In-person, remote and hybrid delivery"], outcomes: "Immediately useful skills, a shared language and lasting team autonomy." },
];

export const methodsEn = [
  { number: "01", title: "Frame", text: "Understand the challenge, map the current state and define measurable outcomes.", deliverables: "Assessment · Target vision · Roadmap · Initial backlog" },
  { number: "02", title: "Design", text: "Co-design the experience, architecture and operating model with business and IT teams.", deliverables: "Journeys · Prototypes · Architecture · Delivery plan" },
  { number: "03", title: "Build", text: "Develop, integrate and test in short iterations with quality built in.", deliverables: "Working product · APIs · Automation · Documentation" },
  { number: "04", title: "Evolve", text: "Deploy, observe, secure and improve based on real usage and data.", deliverables: "Production · Observability · Handover · Improvement" },
];
