export const servicesEn = [
  { id: "consulting", number: "01", title: "Business & Technology Consulting", short: "Business & Technology Consulting", summary: "Clarify, frame and de-risk technology decisions before committing budgets and launching strategic programmes.", tagline: "Make the right technology decisions at the right level of investment.", description: "We support executive, business and IT leaders through decisions that shape the information system for years to come. Our consultants combine strategic vision, current-state analysis, architecture expertise and market insight to compare scenarios, control risk and build an executable roadmap.", capabilities: ["Strategic advisory and technology assessment", "Technology due diligence", "IT, digital and data master plans", "Architecture audit and modernisation roadmap", "Scoping, opportunity and feasibility studies", "Solution, architecture and partner benchmarking", "API Management strategy and governance", "Business cases, roadmaps and programme governance"], outcomes: "Evidence-based decisions, a coherent target architecture, prioritised investments and a controlled roadmap." },
  { id: "digital-data", number: "02", title: "Digital & Data Factory", short: "Digital & Data Factory", summary: "Design and deliver high-impact digital products with tailored hybrid teams and an engagement model aligned with your goals.", tagline: "From idea to run, deliver a useful, robust and sustainable product.", description: "Our Digital & Data Factory delivers products and integration programmes through fixed-price or managed-capacity engagements. Agile governance, incremental releases and continuous client involvement provide visibility throughout delivery. After go-live, we provide corrective and evolutionary application maintenance or transfer skills to make your teams autonomous.", capabilities: ["Product discovery, functional scoping and architecture", "Custom web, mobile, data and AI development", "Integration programmes, APIs and interoperability", "Fixed-price or managed-capacity delivery", "Agile governance and incremental releases", "Quality engineering, test automation and production release", "Corrective and evolutionary application maintenance", "Documentation, knowledge transfer and team autonomy"], outcomes: "A working product delivered with visibility, controlled quality and the right maintenance or handover model." },
  { id: "engineering", number: "03", title: "Squad As Service", short: "Squad As Service", summary: "Strengthen your organisation with qualified, flexible and immediately operational capacity through staff augmentation or managed service centres.", tagline: "Mobilise the right profiles quickly and improve delivery performance.", description: "Squad As Service increases delivery capacity without adding organisational overhead. We assemble teams or provide qualified specialists who integrate with your ways of working under the right operating model: staff augmentation, service centre or augmented squad. Capabilities span product, Agile, architecture, engineering, QA and DevSecOps.", capabilities: ["Managed service centres with governance and commitments", "Staff augmentation and flexible capacity", "Augmented multidisciplinary squads", "Qualified profiles ready to contribute quickly", "Delivery performance improvement", "Architecture cells and technical expertise", "Agile profiles: Product Owners and Scrum Masters", "QA, test automation and built-in quality"], outcomes: "Operational capacity mobilised quickly, more predictable delivery and skills that scale with your roadmap." },
  { id: "cloud-devops", number: "04", title: "DevSecOps & Cloud Engineering", short: "DevSecOps & Cloud Engineering", summary: "Industrialise software delivery and secure production releases with a modern, automated and observable software factory.", tagline: "Turn the delivery platform into an accelerator for quality and security.", description: "We assess, design, implement or migrate software factories using leading DevSecOps practices. From source control to deployment, we automate quality gates, security controls, environment provisioning and observability to shorten lead times and make every release more reliable.", capabilities: ["DevSecOps maturity assessment and current-factory audit", "Target architecture and industrialised software-factory implementation", "Development-chain migration and modernisation", "CI/CD pipelines, GitOps and deployment automation", "SAST, SCA, code analysis and secrets management", "Source-code and artifact repository management", "Infrastructure as Code and automated provisioning", "Kubernetes, OpenShift and platform engineering", "Cloud engineering, observability, SRE and FinOps"], outcomes: "More frequent and secure releases, reproducible environments and better-controlled operations." },
  { id: "academy", number: "05", title: "Paytium Academy", short: "Training & Academy", summary: "Grow your teams’ capabilities through practical training led by field experts.", tagline: "Learn today to build better tomorrow.", description: "Paytium Academy delivers courses in technology, product, data, cloud, Agile and management through practical, contextual learning.", capabilities: ["Inter-company courses", "In-company sessions", "Custom learning journeys", "Hands-on workshops and cases", "Management and operational programmes", "In-person, remote and hybrid delivery"], outcomes: "Immediately useful skills, a shared language and lasting team autonomy." },
];

export const methodsEn = [
  { number: "01", title: "Frame", text: "Understand the challenge, map the current state and define measurable outcomes.", deliverables: "Assessment · Target vision · Roadmap · Initial backlog" },
  { number: "02", title: "Design", text: "Co-design the experience, architecture and operating model with business and IT teams.", deliverables: "Journeys · Prototypes · Architecture · Delivery plan" },
  { number: "03", title: "Build", text: "Develop, integrate and test in short iterations with quality built in.", deliverables: "Working product · APIs · Automation · Documentation" },
  { number: "04", title: "Evolve", text: "Deploy, observe, secure and improve based on real usage and data.", deliverables: "Production · Observability · Handover · Improvement" },
];
