import type { Metadata } from "next";
import { FinalCta, PageHero, SectionHeading } from "../../../components/Sections";
import { Breadcrumbs, PageShell } from "../../../components/SiteShell";
import { servicesEn } from "../../../content/site-en";
import { technologies, workingMethods } from "../../../content/site";

const serviceEntries = servicesEn.filter((service) => service.id !== "academy");

export const metadata: Metadata = { title: "Digital, Data, AI, Cloud & DevOps services in Morocco", description: "Paytium Morocco provides IT consulting, digital products, Data & AI, software engineering, Cloud, DevOps and DevSecOps services.", alternates: { canonical: "/en/services", languages: { "fr-FR": "/services", "en-US": "/en/services" } } };
const groupTitles: Record<string,string> = { "Bases de données": "Databases", "Produit & Agilité": "Product & Agile", "Outils & Plateforme": "Tools & Platforms" };
const methods = ["Start with the problem, users and expected value.", "Explore, prototype and test before scaling.", "Deliver in increments and learn quickly.", "Automate quality, security and delivery.", "Improve through usage and operational data.", "Work with client teams and build autonomy."];

export default function ServicesPage() {
  return <PageShell locale="en" translationHref="/services">
    <Breadcrumbs locale="en" items={[{ label: "Services", href: "/en/services" }]} sections={{ consulting: "Consulting & strategy", "digital-data": "Digital, Data & AI", engineering: "Engineering", "cloud-devops": "Cloud & DevOps", methods: "Ways of working", technologies: "Technologies" }} />
    <PageHero eyebrow="PAYTIUM EXPERTISE" title={<>From vision to operations, <em>end-to-end expertise.</em></>} text="Paytium brings together consulting, product, engineering, data and cloud to design coherent transformations and sustain them over time." primary={["Discuss your project", "/en/#contact"]} secondary={["View our method", "#methods"]}><div className="expertise-visual"><span>Consulting</span><span>Product</span><span>Engineering</span><span>Cloud</span><i /></div></PageHero>
    <section className="section seo-service-intro" aria-labelledby="morocco-expertise"><div><span>PAYTIUM MOROCCO</span><h2 id="morocco-expertise">Digital and technology expertise <em>rooted in Morocco.</em></h2></div><div><p>From Casablanca, Paytium supports businesses, institutions and IT teams across Morocco and internationally. Our consultants connect business priorities, information-system architecture and technology delivery.</p><nav aria-label="Paytium services in Morocco"><a href="#consulting">IT consulting & digital strategy</a><a href="#digital-data">Digital products, Data & AI</a><a href="#engineering">Software engineering</a><a href="#cloud-devops">Cloud, DevOps & DevSecOps</a></nav></div></section>
    <section className="section service-details">{serviceEntries.map((service,index) => <article id={service.id} key={service.id} className="service-detail"><div className="service-index"><span>{service.number}</span><small>EXPERTISE</small></div><div className="service-main"><h2>{service.title}</h2><h3>{service.tagline}</h3><p>{service.description}</p><div className="outcome"><small>EXPECTED OUTCOMES</small><p>{service.outcomes}</p></div></div><div className="capability-list"><small>CAPABILITIES</small>{service.capabilities.map((item,itemIndex) => <div key={item}><span>{String(itemIndex+1).padStart(2,"0")}</span>{item}</div>)}</div>{index < serviceEntries.length-1 && <hr />}</article>)}</section>
    <section className="section working-methods" id="methods"><SectionHeading eyebrow="WAYS OF WORKING" title={<>Methods adapted to the reality <em>of each programme.</em></>} /><div className="method-matrix">{workingMethods.map(([title],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{methods[index]}</p></article>)}</div></section>
    <section className="section technology-library" id="technologies"><SectionHeading eyebrow="TECHNOLOGY STACK" title={<>A modern, open and <em>composable ecosystem.</em></>} text="The stack is selected around needs, client standards and operational constraints — to build a coherent, secure and maintainable solution." /><div className="technology-groups">{technologies.map((group,index) => <article key={group.title}><div><span>{String(index+1).padStart(2,"0")}</span><h3>{groupTitles[group.title] ?? group.title}</h3></div><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>
    <FinalCta eyebrow="BRING THE EXPERTISE TOGETHER" title={<>Need several capabilities focused on <em>one outcome?</em></>} text="Let’s shape a team and roadmap around your context, from initial assessment through production." primary="Talk to Paytium" contactHref="/en/#contact" />
  </PageShell>;
}
