import type { Metadata } from "next";
import { FinalCta, PageHero, SectionHeading } from "../../../components/Sections";
import { Breadcrumbs, PageShell } from "../../../components/SiteShell";
import { servicesEn } from "../../../content/site-en";
import { technologies, workingMethods } from "../../../content/site";

const serviceEntries = servicesEn.filter((service) => service.id !== "academy");

export const metadata: Metadata = { title: "Paytium | Services", description: "Paytium delivers IT consulting, Squad As Service, Data & AI, ERP/API integration, Cloud and DevOps from Casablanca.", alternates: { canonical: "/en/services", languages: { "fr-FR": "/services", "en-US": "/en/services" } } };
const groupTitles: Record<string,string> = { "Ingénierie logicielle": "Software Engineering", "Data & IA": "Data & AI", "API Management & Intégration": "API Management & Integration", "Cybersécurité": "Cybersecurity", "Monitoring & Observabilité": "Monitoring & Observability", "GED & Stockage objet": "Document Management & Object Storage", "Bases de données": "Databases", "Tests & Qualité": "Testing & Quality" };
const methods = ["Start with the problem, users and expected value.", "Explore, prototype and test before scaling.", "Deliver in increments and learn quickly.", "Automate quality, security and delivery.", "Improve through usage and operational data.", "Work with client teams and build autonomy."];

export default function ServicesPage() {
  return <PageShell locale="en" translationHref="/services">
    <Breadcrumbs locale="en" items={[{ label: "Services", href: "/en/services" }]} sections={{ consulting: "Business & Technology Consulting", "digital-data": "Digital & Data Factory", engineering: "Squad As Service", "cloud-devops": "DevSecOps & Cloud Engineering", methods: "Ways of working", expertises: "Our expertise", technologies: "Our expertise" }} />
    <PageHero eyebrow="PAYTIUM EXPERTISE" title={<>From vision to operations, <em>end-to-end expertise.</em></>} text="Paytium brings together consulting, product, Squad As Service, data and cloud to design coherent transformations and sustain them over time." primary={["Discuss your project", "/en/#contact"]} secondary={["View our method", "#methods"]}><div className="expertise-visual"><span>Consulting</span><span>Product</span><span>Squads</span><span>Cloud</span><i /></div></PageHero>
    <section className="section partner-intent"><SectionHeading eyebrow="A TECHNOLOGY PARTNER" title={<>Digital and technology expertise <em>designed around your challenges.</em></>} text="Paytium supports businesses, institutions and IT teams throughout digital transformation programmes. Our consultants connect business priorities, information-system architecture and technology delivery through focused engagements or a multidisciplinary Squad As Service, from discovery through continuous improvement." /><div className="partner-intent-grid">{[["Business & Technology Consulting", "Strategy, information-system assessment, architecture, roadmaps and change enablement."], ["Digital & Data Factory", "Digital products, data platforms, business intelligence, governance, AI use cases and process automation."], ["Squad As Service", "Multidisciplinary product squads, flexible capacity, Agile practices and end-to-end delivery ownership."], ["DevSecOps & Cloud Engineering", "Cloud migration, platform engineering, CI/CD, observability, reliability and built-in security."]].map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="intent-note"><strong>Also preparing your e-invoicing transition?</strong> Explore our <a href="/en/e-invoicing">DGI readiness and ERP/API integration services</a>.</p></section>
    <section className="section service-details">{serviceEntries.map((service,index) => <article id={service.id} key={service.id} className="service-detail"><div className="service-index"><span>{service.number}</span><small>EXPERTISE</small></div><div className="service-main"><h2>{service.title}</h2><h3>{service.tagline}</h3><p>{service.description}</p><div className="outcome"><small>EXPECTED OUTCOMES</small><p>{service.outcomes}</p></div></div><div className="capability-list"><small>CAPABILITIES</small>{service.capabilities.map((item,itemIndex) => <div key={item}><span>{String(itemIndex+1).padStart(2,"0")}</span>{item}</div>)}</div>{index < serviceEntries.length-1 && <hr />}</article>)}</section>
    <section className="section working-methods" id="methods"><SectionHeading eyebrow="WAYS OF WORKING" title={<>Methods adapted to the reality <em>of each programme.</em></>} /><div className="method-matrix">{workingMethods.map(([title],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{methods[index]}</p></article>)}</div></section>
    <section className="section technology-library" id="expertises"><span className="section-anchor" id="technologies" aria-hidden="true" /><SectionHeading eyebrow="OUR EXPERTISE" title={<>Technology stack and <em>areas of expertise.</em></>} text="Our expertise covers the full digital value chain: consulting, software engineering, Data & AI, Cloud, DevSecOps, cybersecurity, integration and product delivery. We shape each stack around your context, standards and operational constraints." /><div className="technology-groups">{technologies.map((group,index) => <article key={group.title}><div><span>{String(index+1).padStart(2,"0")}</span><h3>{groupTitles[group.title] ?? group.title}</h3></div><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>
    <FinalCta eyebrow="BRING THE EXPERTISE TOGETHER" title={<>Need several capabilities focused on <em>one outcome?</em></>} text="Let’s shape a team and roadmap around your context, from initial assessment through production." primary="Talk to Paytium" contactHref="/en/#contact" />
  </PageShell>;
}
