import { LuBuilding2, LuCheck, LuFileText, LuLandmark, LuNetwork, LuSearchCheck, LuWorkflow } from "react-icons/lu";
import { Arrow, Eyebrow } from "./Brand";
import { Breadcrumbs, PageShell } from "./SiteShell";
import { FinalCta, PageHero } from "./Sections";

type Locale = "fr" | "en";
type CaseStudy = { title: string; context: string; capabilities: string[]; value: string; href?: string; cta?: string };
type Domain = { id: string; number: string; label: string; title: string; intro: string; cases: CaseStudy[] };

const frDomains: Domain[] = [
  { id: "e-invoicing", number: "01", label: "Facturation électronique", title: "E-invoicing", intro: "Des plateformes conformes, interopérables et intégrées au système d’information.", cases: [{ title: "E-invoicing", context: "Conception de plateformes de facturation électronique capables de connecter entreprises, systèmes de gestion, prestataires de services et plateformes réglementaires.", capabilities: ["Émission, réception et validation des factures", "Gestion du cycle de vie, des statuts et des événements post-facturation", "Clearance, contrôles métier et pistes d’audit", "Portails web, backoffice, reporting et intégration par API", "Interopérabilité avec les ERP et logiciels de facturation", "Formats XML et UBL, signature électronique, traçabilité et archivage"], value: "Une chaîne de facturation sécurisée, interopérable et conçue pour évoluer avec les exigences réglementaires.", href: "/e-invoicing/", cta: "Découvrir notre solution e-invoicing" }] },
  { id: "payments", number: "02", label: "Paiements & Transaction Banking", title: "Paiements & Transaction Banking", intro: "Des socles transactionnels robustes pour connecter banques, entreprises, partenaires et canaux.", cases: [
    { title: "Cash Management solutions", context: "Digitalisation des échanges entre les entreprises, leurs outils de trésorerie et les systèmes bancaires.", capabilities: ["Initiation et suivi des paiements", "Consultation des relevés, statuts et rapprochements", "Gestion de formats bancaires multiples", "Intégration ERP et Treasury Management System", "Pilotage centralisé des opérations de trésorerie", "Sécurisation, traçabilité et gestion des habilitations"], value: "Une vision consolidée des flux et une automatisation accrue des opérations de trésorerie." },
    { title: "Hub de paiement national et international", context: "Mise en place de hubs centralisant paiements, transferts et services financiers distribués sur plusieurs canaux et entités.", capabilities: ["Paiements nationaux et internationaux et transferts d’argent", "Routage et orchestration des transactions", "Connexion aux banques, opérateurs et systèmes de paiement", "Paramétrage des services et de la tarification", "Traitements en temps réel et par lots", "Réconciliation, compensation, reporting et exposition multicanale"], value: "Un socle transactionnel centralisé facilitant l’intégration de nouveaux services, partenaires et canaux." },
    { title: "Bill Payment & Presentment Hub", context: "Plateformes permettant aux entreprises et administrations de diffuser factures, informations, relevés, relances et appels à l’action auprès de leurs usagers.", capabilities: ["Présentation et paiement de factures", "Appels de paiement immédiats ou différés", "Notifications unitaires ou de masse", "Souscription, annuaires d’organismes et de services", "Parcours multicanaux, traitements online et offline", "Backoffice, suivi, reporting et réconciliation"], value: "Une expérience unifiée pour informer, solliciter et servir les usagers à travers leurs canaux habituels." },
    { title: "Host-to-Host Banking solutions", context: "Connexion sécurisée et automatisée des ERP et systèmes de trésorerie aux plateformes bancaires.", capabilities: ["Transmission de paiements domestiques et internationaux", "Échanges asynchrones sécurisés", "Rapports de statut au niveau fichier et transaction", "Mise à disposition des relevés de comptes", "Formats CSV, ISO 20022 et formats bancaires historiques", "Signature, chiffrement, authentification mutuelle, rejets et rapprochement"], value: "Une intégration bancaire industrialisée réduisant les interventions manuelles et améliorant le suivi des flux." },
    { title: "Migration ISO 20022", context: "Accompagnement des institutions dans la transition progressive de formats historiques vers les messages ISO 20022.", capabilities: ["Cartographie des flux et formats existants", "Messages pain.001, pain.002 et camt.053", "Transformation, validation, statuts et codes de rejet", "Coexistence entre formats historiques et ISO 20022", "Tests d’intégration et de non-régression", "Déploiement progressif et accompagnement des partenaires"], value: "Une migration maîtrisée qui améliore la richesse des données, l’interopérabilité et l’automatisation des traitements." },
  ] },
  { id: "digital-banking", number: "03", label: "Banque digitale & financement", title: "Banque digitale & financement", intro: "Des parcours financiers fluides, sécurisés et cohérents sur l’ensemble des canaux.", cases: [
    { title: "Digital Banking, Selfcare et entrée en relation", context: "Conception et modernisation de parcours bancaires web et mobile à destination des clients, conseillers et administrateurs.", capabilities: ["Internet Banking, Mobile Banking et Selfcare", "Onboarding digital et souscription", "Parcours transactionnels et non transactionnels", "Backoffice siège et agence", "Habilitations, audit trail et API-sation", "Modernisation, migration de données et déploiement multi-entités"], value: "Des parcours cohérents, sécurisés et évolutifs sur l’ensemble des canaux bancaires." },
    { title: "Trade Finance — REDOC, REMDOC et LC", context: "Digitalisation des processus documentaires et des opérations de commerce international.", capabilities: ["Remises documentaires import et export", "Gestion des lettres de crédit", "Constitution et suivi des dossiers", "Contrôles, validations et circuits d’approbation", "Documents, correspondances, statuts et échéances", "Traçabilité et connexion aux backoffices bancaires"], value: "Des opérations de Trade Finance mieux structurées, plus transparentes et plus simples à piloter." },
    { title: "Crédit et financement", context: "Conception de parcours de crédit digitalisés, de la simulation et la demande jusqu’à la décision, au décaissement et au suivi du financement.", capabilities: ["Simulation et demande de crédit", "Collecte des données et documents", "Éligibilité, scoring et règles de décision", "Circuits de validation et notifications", "Mise à disposition des fonds", "Parcours omnicanaux, backoffice et reporting"], value: "Des délais de décision réduits, une expérience emprunteur plus fluide et un traitement des dossiers mieux maîtrisé." },
  ] },
  { id: "orchestration", number: "04", label: "Orchestration & canaux", title: "Orchestration & canaux", intro: "Des processus réutilisables pour industrialiser les services et accélérer leur mise à disposition.", cases: [
    { title: "Orchestrateur de workflows métiers", context: "Industrialisation de services et procédures métiers à travers des workflows configurables et exposables sur plusieurs canaux.", capabilities: ["Modélisation visuelle et workflows BPMN 2.0", "Tâches humaines, automatisations et règles métier", "Circuits de validation pilotables par API", "État, historique et audit des instances", "Paiement, reçus, tickets et documents intégrés", "Simulation multicanale et supervision des traitements"], value: "Une mise sur le marché accélérée des services grâce à des processus réutilisables, configurables et traçables." },
    { title: "Point de vente (POS) et poste opérateur", context: "Modernisation des applications transactionnelles utilisées en agence, dans les réseaux de proximité et aux points de service.", capabilities: ["Paiement de factures, transferts et e-services", "Gestion des caisses", "Authentification et habilitations", "Reçus, justificatifs et traitements en ligne ou hors ligne", "Supervision des transactions", "Backoffice réseau et administration"], value: "Un point de vente unifié pour distribuer davantage de services, accélérer les opérations et sécuriser l’expérience opérateur." },
  ] },
  { id: "api", number: "05", label: "API & interopérabilité", title: "API & interopérabilité", intro: "Une gouvernance d’API conçue pour ouvrir le système d’information sans compromettre sa sécurité.", cases: [{ title: "API Gateway", context: "Mise en place de plateformes d’exposition et de gouvernance d’API ouvertes aux systèmes internes, partenaires et écosystèmes externes.", capabilities: ["Exposition, sécurisation, cycle de vie et versioning des API", "Catalogue, documentation OpenAPI et portail partenaires", "Produits, plans, abonnements et fédération d’identité", "OAuth 2.0, OpenID Connect et mTLS", "Routage, transformation, quotas et contrôle du trafic", "Monitoring, analytics, alerting, résilience et haute disponibilité"], value: "Un accès gouverné et sécurisé aux services, favorisant l’intégration, l’innovation et la création de nouveaux produits digitaux." }] },
  { id: "technical-due-diligence", number: "06", label: "Conseil & Due diligence", title: "Due diligence technique", intro: "Une évaluation indépendante pour sécuriser une décision d’investissement, de transformation ou de rapprochement.", cases: [{ title: "Due diligence d’une plateforme digitale critique", context: "Évaluation transverse d’une plateforme avant une décision stratégique afin d’objectiver sa maturité, identifier les risques techniques et mesurer l’effort nécessaire pour soutenir la trajectoire business.", capabilities: ["Couverture fonctionnelle, scénarios métier et conformité au cahier des charges", "Expérience utilisateur, accessibilité et parcours multicanaux", "Architecture, performance, scalabilité, résilience et points uniques de défaillance", "Qualité du code, Secure SDLC, CI/CD et couverture des tests", "API, interopérabilité, gouvernance Data & IA", "Cybersécurité, IAM, PCA/PRA et référentiels DGSSI, ISO 2700X et EBIOS", "Documentation, exploitation et transfert de compétences", "Entretiens, ateliers ciblés, tests, scoring des risques et roadmap priorisée"], value: "Une vision factuelle et immédiatement exploitable : matrice des risques, recommandations priorisées, estimation des remédiations et synthèse exécutive pour décider avec confiance." }] },
];

const enDomains: Domain[] = [
  { id: "e-invoicing", number: "01", label: "E-invoicing", title: "E-invoicing", intro: "Compliant, interoperable platforms integrated into the information system.", cases: [{ title: "E-invoicing", context: "Design of electronic invoicing platforms connecting businesses, management systems, service providers and regulatory platforms.", capabilities: ["Invoice issuance, receipt and validation", "Lifecycle, status and post-invoicing event management", "Clearance, business controls and audit trails", "Web portals, back office, reporting and API integration", "Interoperability with ERP and invoicing software", "XML and UBL, electronic signatures, traceability and archiving"], value: "A secure, interoperable invoicing chain designed to evolve with regulatory requirements.", href: "/en/e-invoicing/", cta: "Explore our e-invoicing solution" }] },
  { id: "payments", number: "02", label: "Payments & Transaction Banking", title: "Payments & Transaction Banking", intro: "Robust transaction platforms connecting banks, businesses, partners and channels.", cases: [
    { title: "Cash Management solutions", context: "Digitalisation of exchanges between businesses, treasury tools and banking systems.", capabilities: ["Payment initiation and tracking", "Statements, statuses and reconciliation", "Multiple banking formats", "ERP and Treasury Management System integration", "Centralised treasury operations", "Security, traceability and entitlements"], value: "A consolidated view of flows and greater automation of treasury operations." },
    { title: "Domestic and international payment hub", context: "Implementation of hubs centralising payments, transfers and financial services across channels and entities.", capabilities: ["Domestic and international payments and money transfers", "Transaction routing and orchestration", "Connections to banks, operators and payment systems", "Service and pricing configuration", "Real-time and batch processing", "Reconciliation, settlement, reporting and multichannel exposure"], value: "A central transaction foundation that simplifies the addition of services, partners and channels." },
    { title: "Bill Payment & Presentment Hub", context: "Platforms enabling businesses and public organisations to distribute bills, statements, reminders and calls to action.", capabilities: ["Bill presentation and payment", "Immediate or scheduled payment requests", "Individual and bulk notifications", "Subscriptions and service directories", "Multichannel online and offline journeys", "Back office, tracking, reporting and reconciliation"], value: "A unified experience for informing and serving users through their preferred channels." },
    { title: "Host-to-Host Banking solutions", context: "Secure, automated connection of ERP and treasury systems to banking platforms.", capabilities: ["Domestic and international payment transmission", "Secure asynchronous exchanges", "File- and transaction-level status reports", "Account statement delivery", "CSV, ISO 20022 and legacy banking formats", "Signing, encryption, mutual authentication, rejection handling and reconciliation"], value: "Industrialised bank integration that reduces manual work and improves flow tracking." },
    { title: "ISO 20022 migration", context: "Supporting institutions through the progressive transition from legacy formats to ISO 20022 messages.", capabilities: ["Mapping existing flows and formats", "pain.001, pain.002 and camt.053 messages", "Transformation, validation, statuses and rejection codes", "Legacy and ISO 20022 coexistence strategies", "Integration and regression testing", "Phased rollout and partner enablement"], value: "A controlled migration improving data richness, interoperability and processing automation." },
  ] },
  { id: "digital-banking", number: "03", label: "Digital banking & lending", title: "Digital banking & lending", intro: "Seamless, secure financial journeys across every customer and employee channel.", cases: [
    { title: "Digital Banking, Selfcare & onboarding", context: "Design and modernisation of web and mobile banking journeys for customers, advisers and administrators.", capabilities: ["Internet Banking, Mobile Banking and Selfcare", "Digital onboarding and product subscription", "Transactional and non-transactional journeys", "Head-office and branch back offices", "Entitlements, audit trails and API enablement", "Modernisation, data migration and multi-entity rollout"], value: "Consistent, secure and scalable experiences across banking channels." },
    { title: "Trade Finance — REDOC, REMDOC & LC", context: "Digitalisation of documentary processes and international trade operations.", capabilities: ["Import and export documentary collections", "Letter of credit management", "Case creation and monitoring", "Controls, validations and approval workflows", "Documents, correspondence, statuses and deadlines", "Traceability and banking back-office integration"], value: "Better structured, more transparent and easier-to-manage Trade Finance operations." },
    { title: "Digital lending", context: "End-to-end digital lending journeys, from simulation and application through credit decisioning, disbursement and loan servicing.", capabilities: ["Loan simulation and application", "Data and document collection", "Eligibility, credit scoring and decision rules", "Approval workflows and notifications", "Loan disbursement", "Omnichannel journeys, lending operations and reporting"], value: "Faster credit decisions, a smoother borrower experience and greater control over loan processing." },
  ] },
  { id: "orchestration", number: "04", label: "Orchestration & channels", title: "Orchestration & channels", intro: "Reusable processes that industrialise services and accelerate their delivery across channels.", cases: [
    { title: "Business workflow orchestrator", context: "Industrialisation of services and business procedures through configurable, multichannel workflows.", capabilities: ["Visual modelling and BPMN 2.0 workflows", "Human tasks, automation and business rules", "API-driven approval workflows", "Instance status, history and audit", "Embedded payments, receipts, tickets and documents", "Multichannel simulation and processing supervision"], value: "Faster service launches through reusable, configurable and traceable processes." },
    { title: "Point of Sale (POS)", context: "Modernisation of transaction applications used across branches, agent networks and customer service points.", capabilities: ["Bill payment, money transfer and e-services", "Till and cash management", "Authentication and entitlements", "Receipts and online or offline transaction processing", "Transaction monitoring", "Agent network back office and administration"], value: "A unified POS platform that expands service distribution, accelerates operations and improves operator security." },
  ] },
  { id: "api", number: "05", label: "API & interoperability", title: "API & interoperability", intro: "API governance that opens the information system without compromising security.", cases: [{ title: "API Gateway", context: "Implementation of API exposure and governance platforms for internal systems, partners and external ecosystems.", capabilities: ["API exposure, security, lifecycle and versioning", "Catalogue, OpenAPI documentation and partner portal", "Products, plans, subscriptions and identity federation", "OAuth 2.0, OpenID Connect and mTLS", "Routing, transformation, quotas and traffic control", "Monitoring, analytics, alerting, resilience and high availability"], value: "Governed, secure access to services that supports integration, innovation and new digital products." }] },
  { id: "technical-due-diligence", number: "06", label: "Advisory & Due diligence", title: "Technical due diligence", intro: "An independent assessment that de-risks investment, transformation and corporate transaction decisions.", cases: [{ title: "Technical due diligence of a business-critical digital platform", context: "A cross-functional platform assessment ahead of a strategic decision, designed to establish technology maturity, identify material risks and quantify the effort required to support the business roadmap.", capabilities: ["Functional coverage, end-to-end business scenarios and specification compliance", "User experience, accessibility and omnichannel journeys", "Architecture, performance, scalability, resilience and single points of failure", "Code quality, Secure SDLC, CI/CD and automated test coverage", "APIs, interoperability, Data & AI governance", "Cybersecurity, IAM, business continuity and risk frameworks", "Technical documentation, operations and knowledge transfer", "Stakeholder interviews, targeted workshops, testing, risk scoring and prioritised roadmap"], value: "A decision-ready view of the platform: risk matrix, prioritised recommendations, remediation estimates and an executive summary that enables confident action." }] },
];

function DomainIcon({ id }: { id: string }) {
  const Icon = id === "e-invoicing" ? LuFileText : id === "payments" ? LuLandmark : id === "digital-banking" ? LuBuilding2 : id === "orchestration" ? LuWorkflow : id === "technical-due-diligence" ? LuSearchCheck : LuNetwork;
  return <Icon aria-hidden="true" />;
}

export function ExpertiseCasesPage({ locale = "fr" }: { locale?: Locale }) {
  const en = locale === "en";
  const domains = en ? enDomains : frDomains;
  const prefix = en ? "/en" : "";
  const caseNumber = (domainIndex: number, caseIndex: number) => domains.slice(0, domainIndex).reduce((total, domain) => total + domain.cases.length, 0) + caseIndex + 1;
  const copy = en ? {
    breadcrumb: "Case studies", eyebrow: "CASE STUDIES", title: <>Proven delivery across <em>critical digital and financial platforms.</em></>, intro: "Explore selected Paytium engagements where strategic insight and technology execution turned complex challenges into confident decisions, resilient platforms and measurable business outcomes—from technical due diligence to e-invoicing, payments, digital banking and API interoperability.", explore: "Explore our case studies", talk: "Talk to an expert", nav: "Case study areas", caseLabel: "CASE", capabilities: "CAPABILITIES", value: "VALUE DELIVERED", finalTitle: <>Planning a financial or <em>transaction transformation?</em></>, finalText: "Let’s discuss your payment, digital banking, interoperability or process automation priorities.",
  } : {
    breadcrumb: "Études de cas", eyebrow: "ÉTUDES DE CAS", title: <>Des réalisations éprouvées sur des <em>plateformes digitales et financières critiques.</em></>, intro: "Découvrez une sélection de missions où le conseil stratégique et l’exécution technologique Paytium ont transformé des enjeux complexes en décisions sécurisées, plateformes résilientes et résultats mesurables — de la due diligence technique à la facturation électronique, aux paiements, à la banque digitale et à l’interopérabilité API.", explore: "Explorer nos études de cas", talk: "Parler à un expert", nav: "Domaines des études de cas", caseLabel: "CAS", capabilities: "CAPACITÉS", value: "VALEUR APPORTÉE", finalTitle: <>Vous avez un projet de transformation <em>financière ou transactionnelle ?</em></>, finalText: "Échangeons sur vos enjeux de paiement, de banque digitale, d’interopérabilité ou d’automatisation des processus.",
  };

  return <PageShell locale={locale} translationHref={en ? "/case-studies/" : "/en/case-studies/"} activeNav="case-studies">
    <Breadcrumbs locale={locale} items={[{ label: copy.breadcrumb, href: `${prefix}/case-studies/` }]} sections={Object.fromEntries(domains.map((domain) => [domain.id, domain.label]))} />
    <PageHero eyebrow={copy.eyebrow} title={copy.title} text={copy.intro} primary={[copy.explore, "#e-invoicing"]} secondary={[copy.talk, `${prefix}/#contact`]}>
      <div className="expertise-cases-visual" aria-hidden="true"><span>PAY</span><span>API</span><span>ISO</span><span>DATA</span><i><img src="/paytium-icon-white.svg" alt="" /></i></div>
    </PageHero>
    <nav className="expertise-anchor-nav" aria-label={copy.nav}>{domains.map((domain) => <a key={domain.id} href={`#${domain.id}`}><span>{domain.number}</span>{domain.label}</a>)}</nav>
    {domains.map((domain, domainIndex) => <section className={`section expertise-domain domain-${domainIndex + 1}`} id={domain.id} key={domain.id}>
      <header className="expertise-domain-heading"><div><span>{domain.number}</span><i><DomainIcon id={domain.id} /></i></div><div><Eyebrow>{domain.label}</Eyebrow><h2>{domain.title}</h2><p>{domain.intro}</p></div></header>
      <div className="case-study-list">{domain.cases.map((study, index) => <article className={`case-study ${index === 0 ? "case-study-lead" : ""}`} key={study.title}>
        <div className="case-study-copy"><small>{copy.caseLabel} {caseNumber(domainIndex, index)} · {domain.label}</small><h3>{study.title}</h3><p>{study.context}</p>{study.href && <a className="text-link" href={study.href}>{study.cta} <Arrow /></a>}</div>
        <div className="case-study-capabilities"><small>{copy.capabilities}</small><ul>{study.capabilities.map((capability) => <li key={capability}><LuCheck aria-hidden="true" />{capability}</li>)}</ul></div>
        <aside><small>{copy.value}</small><p>{study.value}</p></aside>
      </article>)}</div>
    </section>)}
    <FinalCta eyebrow={en ? "LET’S BUILD THE NEXT PLATFORM" : "CONSTRUISONS LA PROCHAINE PLATEFORME"} title={copy.finalTitle} text={copy.finalText} primary={copy.talk} contactHref={`${prefix}/#contact`} />
  </PageShell>;
}
