import type { Metadata } from "next";
import { Eyebrow } from "../../../components/Brand";
import { FinalCta, PageHero, SectionHeading } from "../../../components/Sections";
import { PageShell } from "../../../components/SiteShell";

export const metadata: Metadata = { title: "E-invoicing integration", description: "Prepare, integrate and industrialise your e-invoicing chain through a progressive approach connected to your information system.", alternates: { canonical: "/en/facturation-electronique", languages: { "fr-FR": "/facturation-electronique", "en-US": "/en/facturation-electronique" } } };
const challenges = [["Readiness","Map flows, stakeholders, formats and gaps."],["Interoperability","Connect ERPs, business applications, partners and exchange platforms."],["Control","Validate data, track statuses and handle exceptions."],["Scalability","Absorb regulatory, functional and volume changes."]];
const lifecycle = [["Collect","Receive invoices or data from configured channels."],["Check","Validate structure, mandatory data and business rules."],["Approve","Apply approval workflows and manage exceptions."],["Exchange","Send or receive through the expected channel and format."],["Reconcile","Synchronise statuses and update finance systems."],["Archive & manage","Retain required evidence and monitor activity."]];
const useCases = [["Customer invoices","Automate issuance, tracking and reconciliation of sales invoices."],["Supplier invoices","Accelerate receipt, checks, approval and accounting integration."],["Multi-entity groups","Harmonise rules while respecting local specificities."],["Partner ecosystems","Support partners with different levels of digital maturity."]];
const faq = [["Can it connect to our ERP?","Yes. The integration method is defined after assessing interfaces, volumes and security constraints. APIs, batch exchanges, events and connectors can be combined."],["Can deployment be progressive?","Yes. A controlled pilot validates flows, controls and operations before wider rollout."],["How are errors managed?","Controls, statuses, notifications and processing queues help qualify and resolve exceptions with full traceability."],["Is compliance guaranteed?","Paytium designs adaptable architecture and processes. Legal, tax and regulatory validation remains coordinated with the client’s competent functions and official sources."]];

export default function ElectronicInvoicingPage() {
  return <PageShell locale="en" translationHref="/facturation-electronique">
    <PageHero eyebrow="E-INVOICING" title={<>Modernise invoice exchanges <em>without interrupting operations.</em></>} text="Paytium helps prepare, integrate and industrialise an e-invoicing chain connected to finance, accounting and business tools." primary={["Assess your readiness", "/en/#contact"]} secondary={["Talk to an expert", "/en/#contact"]}><div className="einvoice-flow"><div>ERP<br/><small>Applications</small></div><i>→</i><div className="active">Checks<br/><small>& orchestration</small></div><i>→</i><div>Issue<br/><small>& receive</small></div><i>→</i><div>Archive<br/><small>& monitor</small></div></div></PageHero>
    <section className="section challenges-section"><SectionHeading eyebrow="A BUSINESS TRANSITION, NOT JUST A TECHNICAL ONE" title={<>Turn an obligation into <em>operational efficiency.</em></>} text="E-invoicing affects processes, data, systems and organisation. Success starts with a clear current-state view and a progressive, secure and measurable integration." /><div className="challenge-grid">{challenges.map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section lifecycle-section"><SectionHeading eyebrow="PROCESSING LIFECYCLE" title={<>Six steps to stay <em>in control.</em></>} /><div className="lifecycle">{lifecycle.map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="integration-section"><div className="integration-copy"><Eyebrow>INFORMATION SYSTEM INTEGRATION</Eyebrow><h2>Connected to your <em>existing ecosystem.</em></h2><p>Integration is shaped around your architecture and constraints, combining APIs, events, batch exchanges, ERP connectors and secure portals as needed.</p></div><div className="ecosystem-map"><div className="ecosystem-core"><img src="/paytium-icon-white.svg" alt=""/><b>Orchestration</b></div>{["ERP & accounting","Procurement & sales","Master data","Payments","Records","Data & reporting"].map((item,index) => <span className={`eco-${index+1}`} key={item}>{item}</span>)}</div></section>
    <section className="section usecase-section"><SectionHeading eyebrow="USE CASES" title={<>Flows adapted to <em>your organisation.</em></>} /><div className="usecase-grid">{useCases.map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section faq-section"><div><Eyebrow>FREQUENTLY ASKED QUESTIONS</Eyebrow><h2>Move forward <em>with clarity.</em></h2></div><div className="faq-list">{faq.map(([question,answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <FinalCta eyebrow="PREPARE THE NEXT STEP" title={<>Where are you in your <em>e-invoicing transition?</em></>} text="Let’s clarify your scope, priorities and dependencies in an initial conversation." primary="Request a conversation" contactHref="/en/#contact" />
  </PageShell>;
}
