import type { Metadata } from "next";
import { LuArrowRight, LuPlus } from "react-icons/lu";
import { Eyebrow } from "../../../components/Brand";
import { FinalCta, PageHero, SectionHeading } from "../../../components/Sections";
import { Breadcrumbs, PageShell } from "../../../components/SiteShell";

export const metadata: Metadata = { title: "Paytium", description: "E-invoice consulting and integration in Morocco: DGI readiness, ERP/API connections, controls, workflows, traceability and archiving with Paytium.", alternates: { canonical: "/en/facturation-electronique", languages: { "fr-FR": "/facturation-electronique", "en-US": "/en/facturation-electronique" } } };
const challenges = [["Readiness","Map flows, stakeholders, formats and gaps."],["Interoperability","Connect ERPs, business applications, partners and exchange platforms."],["Control","Validate data, track statuses and handle exceptions."],["Scalability","Absorb regulatory, functional and volume changes."]];
const lifecycle = [["Collect","Receive invoices or data from configured channels."],["Check","Validate structure, mandatory data and business rules."],["Approve","Apply approval workflows and manage exceptions."],["Exchange","Send or receive through the expected channel and format."],["Reconcile","Synchronise statuses and update finance systems."],["Archive & manage","Retain required evidence and monitor activity."]];
const useCases = [["Customer invoices","Automate issuance, tracking and reconciliation of sales invoices."],["Supplier invoices","Accelerate receipt, checks, approval and accounting integration."],["Multi-entity groups","Harmonise rules while respecting local specificities."],["Partner ecosystems","Support partners with different levels of digital maturity."]];
const terminology = [["E-invoice & e-invoicing", "E-invoice, e-invoicing and the French term e-facture all refer to digital invoice exchange. The exact target format and channel depend on applicable requirements."], ["ERP & accounting", "Invoice data is connected to existing ERPs, accounting software, business applications and master data."], ["APIs & automation", "Checks, approvals, transmissions, status updates and exceptions are orchestrated through traceable workflows."], ["Archiving & monitoring", "Documents, statuses and evidence are organised for operational search, monitoring and auditability."]];
const faq = [["What is the difference between a PDF invoice, an e-invoice and a structured electronic invoice?", "A PDF may be a readable representation without being a structured, machine-processable data flow. A structured electronic invoice enables automated exchange, checks and integration through the selected format and channel."], ["How should an ERP be prepared for DGI e-invoicing in Morocco?", "Preparation starts by mapping flows, data, interfaces and controls. Paytium then identifies priority ERP, accounting and integration changes while keeping the target adaptable to official publications."], ["Does Paytium provide invoicing software or integration services?", "Paytium provides consulting, scoping, architecture, integration and automation. The solution scope — platform, connectors, portal or specific components — is selected around the client’s information system and needs."], ["Which systems can be connected?", "ERPs, accounting tools, procurement and sales applications, master data, records systems, payment solutions and reporting tools can be connected through APIs, files, events or connectors, depending on their capabilities."], ["Can a business prepare before every final requirement is published?", "Yes. Data quality, flow mapping, governance and an adaptable architecture can be prepared while choices that depend on official legislation and specifications remain open."], ["Can deployment be progressive?", "Yes. A controlled pilot validates flows, controls and operations before a wider rollout."], ["Does Paytium guarantee tax compliance?", "Paytium designs adaptable architecture and processes. Legal, tax and regulatory validation remains coordinated with the client’s competent functions and official sources."]];

export default function ElectronicInvoicingPage() {
  return <PageShell locale="en" translationHref="/facturation-electronique">
    <Breadcrumbs locale="en" items={[{ label: "E-invoicing", href: "/en/facturation-electronique" }]} />
    <PageHero eyebrow="E-INVOICING MOROCCO" title={<>Prepare for e-invoicing <em>without interrupting operations.</em></>} text="Paytium helps organisations in Morocco prepare for e-invoicing and DGI-led developments through a chain connected to finance, accounting and business tools." primary={["Assess your readiness", "/en/#contact"]} secondary={["Talk to an expert", "/en/#contact"]}><div className="einvoice-flow"><div>ERP<br/><small>Applications</small></div><i aria-hidden="true"><LuArrowRight /></i><div className="active">Checks<br/><small>& orchestration</small></div><i aria-hidden="true"><LuArrowRight /></i><div>Issue<br/><small>& receive</small></div><i aria-hidden="true"><LuArrowRight /></i><div>Archive<br/><small>& monitor</small></div></div></PageHero>
    <section className="section einvoice-morocco" aria-labelledby="dgi-morocco"><div><Eyebrow>E-INVOICING & MOROCCO DGI</Eyebrow><h2 id="dgi-morocco">Anticipate requirements and <em>prepare your information system.</em></h2></div><div><p>Morocco’s e-invoicing transition involves the Directorate General of Taxes (DGI) as well as finance, tax, procurement, sales and IT teams. Paytium helps map invoice flows, improve data quality and prepare ERP and accounting integrations.</p><p>The target design remains adaptable to officially published legislation, timelines and technical specifications. Paytium does not replace tax advice; compliance decisions stay coordinated with competent client functions and official references.</p><a className="text-link" href="https://www.finances.gov.ma/en/Ministere/Pages/dgi.aspx" target="_blank" rel="noreferrer">View the official DGI presentation <LuArrowRight aria-hidden="true" /></a></div></section>
    <section className="section einvoice-terms" id="e-invoice-morocco"><SectionHeading eyebrow="E-INVOICE, E-INVOICING & E-FACTURE" title={<>One initiative with <em>several business and technology challenges.</em></>} text="Whether your teams search for e-invoice Morocco, e-invoicing Morocco or facturation électronique Maroc, the goal is the same: reliable, interoperable invoice flows that protect business continuity." /><div className="einvoice-term-grid">{terminology.map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="intent-note"><strong>Looking for an e-invoicing integration partner in Morocco?</strong> Paytium supports your journey from readiness assessment and ERP/API integration to rollout and continuous improvement.</p></section>
    <section className="section challenges-section"><SectionHeading eyebrow="A BUSINESS TRANSITION, NOT JUST A TECHNICAL ONE" title={<>Turn an obligation into <em>operational efficiency.</em></>} text="E-invoicing affects processes, data, systems and organisation. Success starts with a clear current-state view and a progressive, secure and measurable integration." /><div className="challenge-grid">{challenges.map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section lifecycle-section"><SectionHeading eyebrow="PROCESSING LIFECYCLE" title={<>Six steps to stay <em>in control.</em></>} /><div className="lifecycle">{lifecycle.map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="integration-section"><div className="integration-copy"><Eyebrow>INFORMATION SYSTEM INTEGRATION</Eyebrow><h2>Connected to your <em>existing ecosystem.</em></h2><p>Integration is shaped around your architecture and constraints, combining APIs, events, batch exchanges, ERP connectors and secure portals as needed.</p></div><div className="ecosystem-map"><div className="ecosystem-core"><img src="/paytium-icon-white.svg" alt=""/><b>Orchestration</b></div>{["ERP & accounting","Procurement & sales","Master data","Payments","Records","Data & reporting"].map((item,index) => <span className={`eco-${index+1}`} key={item}>{item}</span>)}</div></section>
    <section className="section usecase-section"><SectionHeading eyebrow="USE CASES" title={<>Flows adapted to <em>your organisation.</em></>} /><div className="usecase-grid">{useCases.map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section faq-section"><div><Eyebrow>FREQUENTLY ASKED QUESTIONS</Eyebrow><h2>Move forward <em>with clarity.</em></h2></div><div className="faq-list">{faq.map(([question,answer]) => <details key={question}><summary>{question}<span aria-hidden="true"><LuPlus /></span></summary><p>{answer}</p></details>)}</div></section>
    <FinalCta eyebrow="PREPARE THE NEXT STEP" title={<>Where are you in your <em>e-invoicing transition?</em></>} text="Let’s clarify your scope, priorities and dependencies in an initial conversation." primary="Request a conversation" contactHref="/en/#contact" />
  </PageShell>;
}
