import type { Metadata } from "next";
import { FaMicrosoft } from "react-icons/fa6";
import { LuArrowLeft, LuArrowRight, LuCheck, LuDatabase, LuLayers3, LuPlus, LuZap } from "react-icons/lu";
import { SiOdoo, SiSage, SiSap } from "react-icons/si";
import { Breadcrumbs, PageShell } from "../../../components/SiteShell";
import { Arrow, Eyebrow } from "../../../components/Brand";
import { SectionHeading } from "../../../components/Sections";
import { EinvoiceConsultationForm, TrackedLink } from "../../../components/EinvoiceConsultationForm";

export const metadata: Metadata = {
  title: "Paytium | E-Invoicing & DGI Connector",
  description: "Connect ERP and business applications to the e-invoicing ecosystem with Paytium: advisory, bidirectional integration, e-Invoice Connector and CSP support.",
  alternates: { canonical: "/en/e-invoicing", languages: { "fr-FR": "/e-invoicing", "en-US": "/en/e-invoicing" } },
  openGraph: { title: "Paytium | E-Invoicing & DGI Connector", description: "ERP integration and the Paytium e-Invoice Connector to orchestrate electronic invoicing flows from end to end.", url: "/en/e-invoicing", type: "website", locale: "en_US", alternateLocale: ["fr_FR"], siteName: "Paytium", images: [{ url: "/og-einvoicing-casablanca.png", width: 1200, height: 630, alt: "Paytium — E-invoicing and e-Invoice Connector in Casablanca" }] },
  twitter: { card: "summary_large_image", title: "Paytium | E-Invoicing & DGI Connector", description: "Connect your ERP, automate exchanges and secure your e-invoicing journey with Paytium.", images: ["/og-einvoicing-casablanca.png"] },
};

const publicMarkers = [
  ["Structured format", "UBL has been announced as the reference standard. The national version and profile will be confirmed through official specifications."],
  ["Authenticity & integrity", "A qualified electronic signature has been announced to secure invoice origin and integrity."],
  ["Validation & traceability", "The announced flow includes real-time validation, acknowledgements and a reliable receipt date."],
  ["Phased rollout", "B2B has been announced as the initial scope, with the timetable and detailed arrangements still to be confirmed."],
];
const compliancePillars = [["Processes", "Issuance, receipt, credit notes, approvals, exceptions and reconciliation."], ["Data", "Master-data quality, completeness, consistency and traceability."], ["Technology", "ERP integration, interoperability, security, monitoring and resilience."], ["Governance", "Roles, controls, documentation, change management and programme steering."]];
const connectionModes = [["REST APIs", "Modern synchronous or asynchronous integration tailored to each use case."], ["SOAP APIs", "Compatibility with existing applications and enterprise architectures."], ["SFTP / secure transfer", "CFT or SFTP batch exchanges for file-oriented systems."], ["Custom integration", "Dedicated adapters, middleware, ESB, events or proprietary constraints."]];
const connectorCapabilities = ["Invoice and credit-note issuance and receipt", "Data mapping and transformation", "Completeness, consistency and business-rule checks", "Exchange and response orchestration", "Status tracking and error management", "Recovery, idempotency and duplicate handling", "ERP and accounting application synchronisation", "Logging, monitoring, alerts and audit trail", "Payment events where supported by the applicable scope", "Phased rollout by entity, flow, ERP or user population"];
const offers = [
  { title: "Business advisory & readiness", text: "Assess maturity, turn published requirements into operational decisions and build a realistic roadmap.", items: ["Business, data, IT, security and organisation assessment", "Mapping of outbound and inbound invoice flows", "Gap, risk and priority analysis", "ERP, master-data and interface review", "Target design, roadmap, governance and change management"] },
  { title: "Paytium e-Invoice Connector", text: "Connect your systems to the target ecosystem through a supervised, adaptable bidirectional layer.", items: ["ERP connectors and dedicated adapters", "APIs, web services and file exchanges", "Issuance, receipt, statuses and exceptions", "Checks, transformation and orchestration", "Monitoring, traceability and multi-entity rollout"], featured: true },
  { title: "Platform for CSP candidates", text: "Design and industrialise the platform, services and operations required by organisations seeking CSP positioning.", items: ["Operating model and target architecture", "Exchange services, portals and monitoring", "Onboarding, processing, traceability and operations", "Secure, resilient and observable architecture", "Environments, handover and go-live support"] },
  { title: "CSP certification support", text: "Prepare teams, the platform and evidence pack to approach the official process with structure and discipline.", items: ["Functional and technical acceptance", "Test campaigns and defect management", "Quality, security, resilience and operations", "Documentation and evidence preparation", "Mock reviews and remediation plans"] },
  { title: "Programme, data, security & change", text: "Secure the cross-functional dimensions that determine programme success.", items: ["Programme governance and PMO", "Data and master-data quality", "Architecture, cybersecurity and privacy", "Testing, performance and business continuity", "Training, documentation and hypercare"] },
  { title: "Run, support & monitoring", text: "Maintain exchange quality and adapt the solution as official requirements evolve.", items: ["Monitoring and incident handling", "Application support and continuous improvement", "Version and interface management", "Regulatory monitoring and impact assessment", "Control, performance and cost optimisation"] },
];
const deployment = [["Assess", "Flows, systems, data, stakeholders, volumes and risks."], ["Scope", "Target, perimeter, governance, responsibilities and roadmap."], ["Prepare", "Data quality, interfaces, controls and environments."], ["Pilot", "One flow, entity or ERP within a controlled perimeter."], ["Industrialise", "Automation, security, monitoring, documentation and support."], ["Deploy & improve", "Progressive expansion and adaptation to official changes."]];
const whyPaytium = ["Deep understanding of invoicing processes, statuses and operational impacts", "Translation of regulatory requirements into architecture, data, controls and delivery backlog", "ERP, API, middleware, file-transfer and legacy-system integration expertise", "Delivery of secure, observable and scalable platforms", "End-to-end support across advisory, build, certification, deployment and run"];
const faq = [
  ["What is the difference between a PDF and a structured electronic invoice?", "A PDF may be a readable invoice representation without directly usable system data. A structured electronic invoice contains standardised data that can be checked, exchanged and integrated automatically."],
  ["Which features of the Moroccan framework have already been announced?", "Public announcements refer to a UBL-based structured format, qualified electronic signatures, real-time validation, an initial B2B scope and a phased role for certified CSPs. Detailed versions, profiles, rules and timelines remain subject to official publication."],
  ["Is the implementation date for my company already known?", "A rollout during 2026 and a phased deployment have been announced. The precise timetable by company category, activity or market remains subject to official texts. Paytium can already prepare flow mapping, data quality, governance and an adaptable architecture."],
  ["Which invoice format should we prepare?", "UBL has been announced as the international reference. The version, Moroccan profile, required data and control rules must follow officially published specifications. The Paytium Connector is designed to adapt internal formats to the applicable target."],
  ["Does Paytium replace our ERP or invoicing software?", "No. The Paytium e-Invoice Connector sits between your systems and the electronic invoicing channel. It preserves existing user journeys while handling integration, transformation, orchestration and status feedback."],
  ["Does the Connector handle both issuance and receipt?", "Yes. It is positioned as a bidirectional layer for invoices and credit notes, supplier invoice receipt, acknowledgements, statuses, notifications and errors, subject to the officially supported interfaces."],
  ["Which integration modes are available?", "REST APIs, SOAP services, secure CFT or SFTP file exchanges, middleware, events and dedicated connectors. The mode is selected according to architecture, security, volumes and system capabilities."],
  ["Which ERPs can be connected?", "Paytium can connect ERP, accounting, TMS and business applications using connectors, accelerators or dedicated adapters. Exact compatibility is confirmed according to product, version, modules and available integration options."],
  ["Can we start before all specifications are published?", "Yes. Readiness, flow mapping, master-data quality, governance and an adaptable architecture can be addressed now while choices dependent on final texts remain open."],
  ["How does Paytium support CSP candidates?", "Paytium supports scoping, architecture, development, testing, security, data governance, operations and evidence preparation. The objective is to accelerate and secure the journey without guaranteeing a decision made by the certification authority."],
  ["How are security and data protection addressed?", "The solution is shaped around client context and applicable requirements, including access control, exchange encryption, logging, segregation of duties, monitoring, continuity and personal-data protection."],
  ["What does the free 30-minute consultation cover?", "It helps us understand your context, identify major gaps and recommend the most useful next step. It is not a full audit or legal or tax advice."],
];
const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", "@id": "https://paytium.io/en/e-invoicing#service", name: "E-invoicing & Paytium e-Invoice Connector", serviceType: "E-invoicing advisory and integration", provider: { "@id": "https://paytium.io/#organization" }, areaServed: { "@type": "Country", name: "Morocco" }, url: "https://paytium.io/en/e-invoicing", description: metadata.description }, { "@type": "FAQPage", "@id": "https://paytium.io/en/e-invoicing#faq", mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] };

export default function ElectronicInvoicingPage() {
  return <PageShell locale="en" translationHref="/e-invoicing">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <Breadcrumbs locale="en" items={[{ label: "E-invoicing", href: "/en/e-invoicing" }]} sections={{ connector: "Connector", offres: "Solutions", consultation: "Consultation", faq: "FAQ" }} />
    <section className="einvoice-hero"><div className="einvoice-hero-copy"><Eyebrow className="page-kicker">E-INVOICING</Eyebrow><h1>Connect your invoicing systems to the DGI ecosystem, <em>without disrupting operations.</em></h1><p>Paytium supports organisations from readiness assessment through operational integration. The Paytium e-Invoice Connector creates a bidirectional gateway between ERP, TMS, accounting and business applications, and the electronic invoicing ecosystem.</p><p className="einvoice-proof">Business & regulatory advisory · ERP integration · Connector · CSP platforms · Certification support</p><div className="hero-actions"><TrackedLink className="button button-primary" href="#consultation" eventName="einvoice_hero_cta_click">Book my free 30-minute consultation <Arrow /></TrackedLink><TrackedLink className="button button-secondary" href="#connector" eventName="einvoice_connector_cta_click">Discover the Connector</TrackedLink></div><div className="einvoice-consultation-note"><b>Free consultation · 30 minutes</b><span>A no-obligation discussion to clarify your scope, risks and next steps.</span></div></div><figure className="einvoice-hero-media"><img src="/einvoicing-casablanca.jpg" alt="Moroccan architecture in Casablanca" width="2400" height="1594" fetchPriority="high" /><div className="einvoice-hero-badges" aria-label="Morocco and Directorate General of Taxes"><span><img src="/flag-morocco.png" alt="Flag of Morocco" width="56" height="36" /><small>MOROCCO</small></span><span><img src="/logo-dgi.png" alt="Directorate General of Taxes logo" width="56" height="56" /><small>DGI</small></span></div><figcaption>Casablanca · Photo <a href="https://unsplash.com/@hansjuergen" target="_blank" rel="noopener noreferrer">Hans-Jürgen Weinhardt</a> / Unsplash</figcaption></figure></section>
    <section className="section einvoice-erp-section"><SectionHeading eyebrow="BUILT FOR YOUR ECOSYSTEM" title={<>Your ERP remains at the heart <em>of operations.</em></>} text="Paytium adapts to existing systems and protects finance, procurement and sales processes. Connectors or integration accelerators are selected according to each ERP, version and module set." /><div className="erp-logo-grid" aria-label="Examples of systems that can be integrated"><div><SiSap aria-hidden="true" /><span>SAP</span></div><div><LuDatabase aria-hidden="true" /><span>Oracle</span></div><div><LuDatabase aria-hidden="true" /><span>Oracle NetSuite</span></div><div><FaMicrosoft aria-hidden="true" /><span>Dynamics 365</span></div><div><SiSage aria-hidden="true" /><span>Sage</span></div><div><SiOdoo aria-hidden="true" /><span>Odoo</span></div><div><LuLayers3 aria-hidden="true" /><span>Cegid</span></div><div><LuLayers3 aria-hidden="true" /><span>Infor</span></div></div><p className="brand-disclaimer">Brands are shown for illustration. Connector availability and scope are confirmed according to system version and client architecture. All trademarks belong to their respective owners.</p></section>
    <section className="section einvoice-context-section"><SectionHeading invert eyebrow="THE MOROCCAN CONTEXT" title={<>Structured, secure invoicing <em>integrated with your systems.</em></>} text="Electronic invoicing turns the invoice into an end-to-end data flow. Public DGI announcements describe structured B2B invoices exchanged through secure, traceable channels." /><div className="public-marker-grid">{publicMarkers.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section einvoice-compliance-section"><SectionHeading eyebrow="YOUR READINESS JOURNEY" title={<>From regulatory requirements to <em>an operational solution.</em></>} text="Paytium turns applicable requirements into processes, data, controls, interfaces and evidence. The goal is to align invoicing flows while protecting operational continuity." /><div className="compliance-pillar-grid">{compliancePillars.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="responsible-note">Legal and tax validation remains coordinated with the client’s relevant teams and current official texts.</p></section>
    <section className="section connector-positioning" aria-labelledby="connector-positioning-title"><div className="connector-positioning-copy"><div><Eyebrow className="page-kicker">BIDIRECTIONAL INTEROPERABILITY</Eyebrow><h2 id="connector-positioning-title">Paytium e-Invoice Connector : your gateway to the DGI e-invoicing ecosystem.</h2></div><p>A single integration layer orchestrates both directions without replacing your tools. It adapts data and protocols to the expected channel, then returns received invoices, acknowledgements, statuses and errors to your applications.</p></div><div className="connector-diagram" aria-label="Bidirectional Paytium e-Invoice Connector functional diagram"><div className="connector-node"><small>ENTERPRISE SYSTEMS</small><b>ERP · TMS · Accounting</b><span>Procurement · Sales · Business apps · Files</span></div><div className="connector-flows"><span><LuArrowRight aria-hidden="true" />Outbound flows</span><span><LuArrowLeft aria-hidden="true" />Inbound flows</span></div><div className="connector-node connector-core"><img src="/paytium-icon-white.svg" alt="" width="44" height="44" /><small>PAYTIUM E-INVOICE CONNECTOR</small><b>Collect · Check · Transform</b><span>Orchestrate · Exchange · Monitor</span></div><div className="connector-flows"><span><LuArrowRight aria-hidden="true" />Invoices · credit notes · data</span><span><LuArrowLeft aria-hidden="true" />Acknowledgements · statuses · errors</span></div><div className="connector-node"><small>DGI / CSP ECOSYSTEM</small><b>Validation · Exchange</b><span>Acknowledgements · Statuses · Customers · Suppliers</span></div></div></section>
    <section className="section connector-detail" id="connector"><SectionHeading eyebrow="PAYTIUM E-INVOICE CONNECTOR" title={<>Transparent integration, <em>whatever your starting point.</em></>} text="The Connector absorbs system heterogeneity and centralises orchestration. Teams keep working in familiar tools while the Paytium layer manages transformations, checks, exchanges and feedback." /><div className="connection-mode-grid">{connectionModes.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="connector-capability-layout"><div><h3>Connector capabilities</h3><p>An integration foundation designed to evolve with your architecture and official publications.</p><div className="connector-promises"><strong>Your ERP is not replaced.</strong><strong>Users retain their usual tools.</strong><strong>Integration evolves with official publications.</strong></div></div><ul>{connectorCapabilities.map((item) => <li key={item}><LuCheck aria-hidden="true" />{item}</li>)}</ul></div><TrackedLink className="button button-primary connector-cta" href="#consultation" eventName="einvoice_connector_cta_click">Assess my integration architecture <Arrow /></TrackedLink></section>
    <section className="section einvoice-offers" id="offres"><SectionHeading invert eyebrow="SOLUTIONS MATCHED TO YOUR AMBITION" title={<>From assessment to deployment, <em>through the CSP journey.</em></>} text="Modular support to prepare teams, integrate systems or build and secure a CSP journey." /><div className="einvoice-offer-grid">{offers.map((offer, index) => <article className={offer.featured ? "featured" : ""} key={offer.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{offer.title}</h3><p>{offer.text}</p><ul>{offer.items.map((item) => <li key={item}><LuCheck aria-hidden="true" />{item}</li>)}</ul>{index === 2 && <small>Objective : accelerate and secure the journey without promising a certification timeline.</small>}</article>)}</div></section>
    <section className="section einvoice-deployment"><SectionHeading eyebrow="DEPLOYMENT APPROACH" title={<>A progressive, measurable and <em>controlled journey.</em></>} text="Paytium works alongside your teams to reduce risk, protect business continuity and build autonomy." /><div className="einvoice-deployment-track">{deployment.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section why-paytium-section"><div><Eyebrow className="page-kicker">WHY PAYTIUM</Eyebrow><h2>Combined <em>business and technology expertise.</em></h2><p>From scoping through operations, we bring together the capabilities required to turn a complex requirement into a usable, observable and durable solution.</p></div><ol>{whyPaytium.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></section>
    <section className="section einvoice-consultation" id="consultation"><div className="consultation-copy"><Eyebrow className="page-kicker">FREE CONSULTATION · 30 MINUTES</Eyebrow><h2>Where are you in your <em>e-invoicing journey?</em></h2><p>Speak with a Paytium expert to clarify your context, identify major gaps and select the most useful next step — assessment, Connector integration, CSP platform or certification preparation.</p><div className="consultation-agenda"><span><b>5 min</b>Your context, systems and priorities</span><span><b>15 min</b>Risks, dependencies and architecture options</span><span><b>10 min</b>Initial recommendations and next steps</span></div><div className="after-consultation"><h3>After the consultation</h3><p><b>01 · Summary</b> Key issues identified.</p><p><b>02 · Direction</b> Recommended journey.</p><p><b>03 · Focused proposal</b> Tailored scope and steps if you wish to continue.</p></div></div><EinvoiceConsultationForm locale="en" /></section>
    <section className="section faq-section einvoice-faq" id="faq"><div><Eyebrow>FREQUENTLY ASKED QUESTIONS</Eyebrow><h2>Move forward with <em>clarity and care.</em></h2><p>Answers distinguish published announcements from details that still require official confirmation.</p></div><div className="faq-list">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true"><LuPlus /></span></summary><p>{answer}</p></details>)}</div></section>
    <TrackedLink className="einvoice-mobile-cta" href="#consultation" eventName="einvoice_hero_cta_click"><LuZap aria-hidden="true" />Free consultation — 30 min</TrackedLink>
  </PageShell>;
}
