import type { Metadata } from "next";
import { FaLinkedinIn } from "react-icons/fa6";
import { LuCheck, LuMail, LuMapPin, LuPhone, LuPlus } from "react-icons/lu";
import { Arrow, Eyebrow, OrbitMark } from "../../components/Brand";
import { ContactForm } from "../../components/ContactForm";
import { HomeHero } from "../../components/HomeHero";
import { FinalCta, SectionHeading, TechPreview } from "../../components/Sections";
import { PageShell } from "../../components/SiteShell";
import { methodsEn, servicesEn } from "../../content/site-en";
import { siteConfig } from "../../content/site";

export const metadata: Metadata = { title: "Paytium Morocco — IT consulting & digital engineering", description: "IT consulting and digital engineering company in Casablanca for strategy, custom software, Data & AI, Cloud, DevOps and e-invoicing.", alternates: { canonical: "/en", languages: { "fr-FR": "/", "en-US": "/en" } } };
const homeServices = servicesEn.filter((service) => service.id !== "academy");

export default function EnglishHomePage() {
  return <PageShell locale="en" translationHref="/">
    <HomeHero locale="en" />
    <nav className="quick-links" aria-label="Quick access">{[["E-invoicing","/en/facturation-electronique","01"],["Consulting & strategy","/en/services#consulting","02"],["Digital, Data & AI","/en/services#digital-data","03"],["Paytium Academy","/en/academy","04"],["Discuss your project","/en/#contact","05"]].map(([label,href,number]) => <a key={label} href={href}><span>{number}</span>{label}<b><Arrow /></b></a>)}</nav>
    <section className="section value-section"><SectionHeading eyebrow="A CLEARER DIGITAL ROADMAP" title={<>From business ambition to a solution <em>that works.</em></>} text="Paytium brings together consulting, design, software engineering, data and cloud to simplify decisions, accelerate delivery and build lasting solutions." /><div className="editorial-cards">{[["01","Clarify","Align business priorities, constraints and technology direction before investing."],["02","Build","Design and develop digital products focused on usefulness, quality and performance."],["03","Evolve","Industrialise, secure and continuously improve platforms, data and operations."]].map(([n,t,p]) => <article key={t}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
    <section className="section about-section" id="a-propos"><div className="about-copy"><Eyebrow>ABOUT PAYTIUM</Eyebrow><h2>A committed partner in your <em>transformation.</em></h2><p>Paytium is an IT consulting and digital engineering company based in Casablanca. We help organisations design, deliver and evolve digital initiatives by connecting business understanding, technology excellence and hands-on collaboration.</p><blockquote>Our mission is to make technology more useful, clearer and more effective for businesses, employees and customers.</blockquote></div><div className="about-visual"><OrbitMark /><div className="discipline-stack"><span>Consulting</span><span>Design</span><span>Engineering</span><span>Run</span></div></div><div className="values-row">{[["Clarity","Make choices, priorities and outcomes understandable."],["Commitment","Work alongside your teams and move forward transparently."],["Excellence","Prioritise quality, security, maintainability and continuous improvement."]].map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section services-home"><SectionHeading eyebrow="OUR SERVICES" title={<>We accelerate your <em>digital transformation.</em></>} /><div className="service-grid">{homeServices.map((service) => <article className={`service-card service-${service.number}`} key={service.id}><span>{service.number}</span><h3>{service.title}</h3><p>{service.summary}</p><ul>{service.capabilities.slice(0,5).map((item) => <li key={item}><LuPlus aria-hidden="true" />{item}</li>)}</ul><a href={`/en/services#${service.id}`} aria-label={`Discover ${service.title}`}><Arrow /></a></article>)}</div><a className="button button-primary section-action" href="/en/services">View all services <Arrow /></a></section>
    <section className="section method-section" id="methode"><SectionHeading eyebrow="AN END-TO-END METHOD" title={<>Move quickly without losing <em>control.</em></>} text="Our approach combines product thinking, Agile, DevSecOps and continuous improvement, adapted to each organisation’s maturity and constraints." /><div className="method-timeline">{methodsEn.map((method) => <article key={method.number}><span>{method.number}</span><h3>{method.title}</h3><p>{method.text}</p><small>{method.deliverables}</small></article>)}</div></section>
    <section className="section tech-section"><SectionHeading eyebrow="TECHNOLOGIES" title={<>Technology chosen for the need, <em>not the other way round.</em></>} text="We assemble modern, open and maintainable architectures around business context, existing systems, security and growth goals." /><TechPreview locale="en" /><a className="text-link" href="/en/services#technologies">Explore our stack and methods <Arrow /></a></section>
    <FinalCta eyebrow="YOUR NEXT STEP STARTS HERE" title={<>A transformation project <em>to bring to life?</em></>} text="Let’s discuss your priorities, constraints and the best path from idea to an operational solution." primary="Start a conversation" contactHref="/en/#contact" />
    <section className="section contact-section" id="contact"><div className="contact-intro"><Eyebrow>CONTACT</Eyebrow><h2>Let’s discuss your <em>next project.</em></h2><p>An idea, challenge or transformation to accelerate? Let’s turn your ambition into concrete next steps.</p><ul>{["A conversation focused on your context", "A clear approach without unnecessary jargon", "The right expertise for the need", "A pragmatic, progressive roadmap"].map((item) => <li key={item}><LuCheck aria-hidden="true" />{item}</li>)}</ul><address className="contact-details"><a href={`mailto:${siteConfig.contactEmail}`}><span aria-hidden="true"><LuMail /></span><small>Email</small><b>{siteConfig.contactEmail}</b></a><a href={`tel:${siteConfig.contactPhone?.replace(/[^\d+]/g, "")}`}><span aria-hidden="true"><LuPhone /></span><small>Phone</small><b>{siteConfig.contactPhone}</b></a><div><span aria-hidden="true"><LuMapPin /></span><small>Address</small><b>{siteConfig.addressEn}</b></div>{siteConfig.linkedinUrl && <a className="linkedin-detail" href={siteConfig.linkedinUrl} target="_blank" rel="noreferrer"><span className="linkedin-icon" aria-hidden="true"><FaLinkedinIn /></span><small>Professional network</small><b>Follow Paytium on LinkedIn</b></a>}</address></div><ContactForm locale="en" /></section>
  </PageShell>;
}
