import type { Metadata } from "next";
import { LuArrowRight, LuPlus } from "react-icons/lu";
import { Breadcrumbs, PageShell } from "../../components/SiteShell";
import { Eyebrow } from "../../components/Brand";
import { FinalCta, PageHero, SectionHeading } from "../../components/Sections";

export const metadata: Metadata = {
  title: "Paytium | Facturation électronique",
  description: "Conseil et intégration e-facture : préparation DGI, connexion ERP/API, contrôles, workflows, traçabilité et archivage avec Paytium.",
  alternates: { canonical: "/e-invoicing", languages: { "fr-FR": "/e-invoicing", "en-US": "/en/e-invoicing" } },
};

const challenges = [["Préparation", "Cartographier les flux, les acteurs, les formats et les écarts."], ["Interopérabilité", "Connecter ERP, applications métier, partenaires et plateformes d’échange."], ["Maîtrise", "Contrôler les données, suivre les statuts et traiter les exceptions."], ["Évolutivité", "Absorber les changements réglementaires, fonctionnels et volumétriques."]];
const lifecycle = [["Collecter", "Recevoir la facture ou les données depuis les canaux configurés."], ["Contrôler", "Vérifier la structure, les données obligatoires et les règles métier."], ["Valider", "Appliquer les circuits d’approbation et gérer les exceptions."], ["Échanger", "Transmettre ou recevoir via le canal et le format attendus."], ["Rapprocher", "Synchroniser les statuts et alimenter les systèmes comptables."], ["Archiver & piloter", "Conserver les éléments requis et suivre l’activité."]];
const capabilities = ["Émission et réception de factures électroniques", "Import depuis ERP, fichiers, APIs ou portail", "Contrôles de complétude, cohérence et règles métier", "Enrichissement et normalisation des données", "Workflows de validation et gestion des exceptions", "Transmission, accusés, statuts et notifications", "Rapprochement comptable et de paiement", "Archivage, recherche et piste d’audit", "Tableaux de bord et supervision opérationnelle"];
const security = ["Accès par rôles et séparation des responsabilités", "Chiffrement des échanges et protection des données", "Journalisation des actions, statuts et erreurs", "Intégrité et traçabilité des documents", "Conservation et archivage configurables", "Supervision, alertes et traitement des exceptions", "Adaptation aux exigences applicables"];
const useCases = [["Factures clients", "Automatiser l’émission, le suivi et la réconciliation des factures de vente."], ["Factures fournisseurs", "Accélérer la réception, le contrôle, l’approbation et l’intégration comptable."], ["Groupes multi-entités", "Harmoniser les règles et consolider le pilotage en respectant les spécificités locales."], ["Écosystèmes partenaires", "Proposer des canaux adaptés à des partenaires de maturités différentes."]];
const deployment = [["Diagnostic", "Flux, données, outils, acteurs, volumes et risques."], ["Cible", "Architecture, processus, modèle opérationnel et feuille de route."], ["Pilote", "Périmètre contrôlé, intégrations prioritaires et mesure."], ["Industrialisation", "Automatisation, sécurité, supervision et documentation."], ["Déploiement", "Extension par entité, population, flux ou cas d’usage."], ["Amélioration continue", "Suivi, assistance, optimisation et évolutions."]];
const terminology = [["E-facture & e-invoice", "Les termes e-facture, e-invoice et e-invoicing désignent la digitalisation des échanges de factures. Le format et le canal cibles sont confirmés selon les exigences applicables."], ["ERP & comptabilité", "Les données de facturation sont reliées aux ERP, logiciels comptables, applications métier et référentiels existants."], ["API & automatisation", "Les contrôles, validations, transmissions, retours de statut et exceptions sont orchestrés dans des workflows traçables."], ["Archivage & pilotage", "Les documents, statuts et preuves sont organisés pour faciliter la recherche, le suivi opérationnel et l’audit."]];
const faq = [["Quelle différence entre une facture PDF, une e-facture et une facture électronique structurée ?", "Un PDF peut être une représentation lisible d’une facture sans être un flux de données structuré et directement exploitable. Une facture électronique structurée permet l’échange, le contrôle et l’intégration automatisés selon le format et le canal retenus."], ["Comment préparer son ERP à la facturation électronique DGI ?", "La préparation commence par la cartographie des flux, des données, des interfaces et des contrôles. Paytium identifie ensuite les adaptations ERP, comptables et d’intégration à prioriser, en gardant la cible adaptable aux publications officielles."], ["Paytium propose-t-il un logiciel de facturation ou un accompagnement d’intégration ?", "Paytium intervient en conseil, cadrage, architecture, intégration et automatisation. Le périmètre de solution — plateforme, connecteurs, portail ou composants spécifiques — est défini selon le système d’information et le besoin du client."], ["Quels systèmes peuvent être connectés ?", "ERP, logiciels comptables, applications achats et ventes, référentiels, GED, solutions de paiement et outils de reporting peuvent être reliés par API, fichiers, événements ou connecteurs, selon leurs capacités."], ["Peut-on préparer le projet avant la publication définitive de toutes les exigences ?", "Oui. Il est possible de fiabiliser les données, cartographier les flux, clarifier la gouvernance et préparer une architecture évolutive, tout en réservant les choix dépendant des textes et spécifications officiels."], ["Peut-on déployer progressivement ?", "Oui. Une approche pilote permet de valider les flux, les contrôles et l’exploitation avant d’étendre le dispositif à d’autres entités ou volumes."], ["Paytium garantit-il la conformité fiscale ?", "Paytium conçoit une architecture et des processus adaptables. La validation juridique, fiscale et réglementaire reste menée avec les fonctions compétentes du client et sur la base des référentiels officiels en vigueur."]];

export default function ElectronicInvoicingPage() {
  return <PageShell translationHref="/en/e-invoicing">
    <Breadcrumbs items={[{ label: "Facturation électronique", href: "/e-invoicing" }]} />
    <PageHero eyebrow="FACTURATION ÉLECTRONIQUE" title={<>Préparez votre facturation électronique, <em>sans interrompre vos opérations.</em></>} text="Paytium accompagne les entreprises dans la préparation à la facturation électronique et aux évolutions portées par la DGI, avec une chaîne connectée aux outils finance, comptables et métier." primary={["Évaluer votre niveau de préparation", "/#contact"]} secondary={["Parler à un expert", "/#contact"]}>
      <div className="einvoice-flow"><div>ERP<br/><small>Applications</small></div><i aria-hidden="true"><LuArrowRight /></i><div className="active">Contrôle<br/><small>& orchestration</small></div><i aria-hidden="true"><LuArrowRight /></i><div>Émission<br/><small>& réception</small></div><i aria-hidden="true"><LuArrowRight /></i><div>Archivage<br/><small>& pilotage</small></div></div>
    </PageHero>

    <section className="section einvoice-readiness" aria-labelledby="dgi-readiness">
      <div><Eyebrow>FACTURATION ÉLECTRONIQUE & DGI</Eyebrow><h2 id="dgi-readiness">Anticiper les exigences, <em>préparer le système d’information.</em></h2></div>
      <div><p>La transition vers la facturation électronique implique la Direction Générale des Impôts (DGI), mais aussi les équipes finance, fiscalité, achats, ventes et IT. Paytium aide à cartographier les flux, fiabiliser les données et préparer les adaptations ERP et comptables.</p><p>Le dispositif est conçu pour rester adaptable aux textes, calendriers et spécifications officiellement publiés. Paytium ne se substitue pas au conseil fiscal : chaque décision de conformité est validée avec les fonctions compétentes et les référentiels officiels.</p><a className="text-link" href="https://www.finances.gov.ma/fr/Ministere/Pages/dgi.aspx" target="_blank" rel="noreferrer">Consulter la présentation officielle de la DGI <LuArrowRight aria-hidden="true" /></a></div>
    </section>

    <section className="section einvoice-terms" id="e-facture">
      <SectionHeading eyebrow="E-FACTURE, E-INVOICE & E-INVOICING" title={<>Un même projet, <em>plusieurs enjeux métier et techniques.</em></>} text="Que vos équipes parlent d’e-facture, d’e-invoice, d’e-invoicing ou de facturation électronique DGI, l’objectif est le même : rendre les flux fiables, interopérables et exploitables sans fragiliser les opérations." />
      <div className="einvoice-term-grid">{terminology.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
      <p className="intent-note"><strong>Besoin d’un intégrateur de facturation électronique ?</strong> Paytium vous accompagne du diagnostic à l’intégration ERP/API, puis au déploiement et à l’amélioration continue.</p>
    </section>

    <section className="section challenges-section">
      <SectionHeading eyebrow="UNE TRANSITION MÉTIER, PAS SEULEMENT TECHNIQUE" title={<>Transformer une obligation en <em>levier d’efficacité.</em></>} text="La facturation électronique touche les processus, les données, les systèmes et l’organisation. Une transition réussie commence par une vision claire de l’existant et se poursuit par une intégration progressive, sécurisée et mesurable." />
      <div className="challenge-grid">{challenges.map(([title,text], index) => <article key={title}><span>{String(index + 1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
    </section>

    <section className="section invoice-capabilities">
      <div><Eyebrow>CHAÎNE DE VALEUR</Eyebrow><h2>Une chaîne de facturation pensée <em>de bout en bout.</em></h2><p>Notre approche combine conseil, intégration et ingénierie pour fluidifier le cycle de vie de la facture, depuis sa création ou sa réception jusqu’au suivi, au rapprochement et à l’archivage.</p></div>
      <ol>{capabilities.map((item,index) => <li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol>
    </section>

    <section className="section lifecycle-section"><SectionHeading eyebrow="CYCLE DE TRAITEMENT" title={<>Six étapes pour garder <em>la maîtrise.</em></>} /><div className="lifecycle">{lifecycle.map(([title,text],index) => <article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="integration-section"><div className="integration-copy"><Eyebrow>INTÉGRATION AU SI</Eyebrow><h2>Connectée à votre <em>écosystème existant.</em></h2><p>L’intégration est définie à partir de votre architecture et de vos contraintes. Elle peut associer APIs, événements, échanges batch, connecteurs ERP et portail sécurisé.</p><small>Les formats, protocoles et connecteurs définitifs sont validés lors du cadrage technique.</small></div><div className="ecosystem-map"><div className="ecosystem-core"><img src="/paytium-icon-white.svg" alt=""/><b>Orchestration</b></div>{["ERP & comptabilité", "Achats & ventes", "Référentiels", "Paiement", "GED & archivage", "Data & reporting"].map((item,index)=><span className={`eco-${index+1}`} key={item}>{item}</span>)}</div></section>

    <section className="section security-section"><SectionHeading eyebrow="SÉCURITÉ, TRAÇABILITÉ & CONFORMITÉ" title={<>La maîtrise intégrée à <em>chaque échange.</em></>} /><div className="security-grid">{security.map((item,index)=><article key={item}><span>0{index+1}</span><p>{item}</p></article>)}</div><p className="responsible-note">Le périmètre de conformité est défini avec les équipes juridique, fiscale, sécurité et protection des données du client, à partir des textes et référentiels officiellement applicables.</p></section>

    <section className="section usecase-section"><SectionHeading eyebrow="CAS D’USAGE" title={<>Des flux adaptés à <em>votre organisation.</em></>} /><div className="usecase-grid">{useCases.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="section deployment-section"><SectionHeading eyebrow="DÉPLOIEMENT" title={<>Une transition progressive <em>et maîtrisée.</em></>} /><div className="deployment-track">{deployment.map(([title,text],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="section faq-section"><div><Eyebrow>QUESTIONS FRÉQUENTES</Eyebrow><h2>Pour avancer avec <em>clarté.</em></h2></div><div className="faq-list">{faq.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true"><LuPlus /></span></summary><p>{answer}</p></details>)}</div></section>

    <FinalCta eyebrow="PRÉPAREZ LA SUITE" title={<>Où en êtes-vous dans votre transition vers la <em>facturation électronique ?</em></>} text="Réalisons un premier échange pour clarifier votre périmètre, vos priorités et les dépendances à anticiper." primary="Demander un échange" secondary={["Découvrir les services Paytium", "/services"]} />
  </PageShell>;
}
